### ISSUE TITLE
server: _id is not doc._id

### ISSUE THREAD

**Issue by krawalli** [aslagle/reactive-table#151]
On using server "auto"-publish, the this._id you may get from row (like described in example) is not the original _id field from document. 

The tableId seems automaticly been added.

What about add a _origId with the original value?

**Comment by aslagle** [comment]
Thanks, you're right. I was trying to fix a bug where docs wouldn't update if they were in the previous subscription by giving them a different id. It would be easy to add an origId, but there might be a better way to preserve the _id.

**Comment by justrag** [comment]
It's a big problem right now if you want to generate links to edit action, for example.

**Comment by aslagle** [comment]
Agreed, I'm working on this next.

**Comment by aslagle** [comment]
Fixed in version 0.6.7.
