### ISSUE TITLE
Table column header templates

### ISSUE THREAD

**Issue by rjsmith** [aslagle/reactive-table#154]
Hi,

I have a use case for dynamically switching content in table header elements.  The content will include Spacebar inclusion tags (ie. sub-templates).   That is why I don't think the `label` function will be adequate.  This is so I can switch the table from 'read' mode to 'edit' mode, where users need to be able to edit the header column text.  I would like to be able to specify something like this:

```javascript
{
  key: 'aHeader',
  labelTmpl: Template.myHeaderTemplate,
  labelData: {some: 'object'},  // Injected as data context into myHeaderTemplate
  tmpl: Template.myCellTemplate
}
```

and:

```html
<template name='myHeaderTemplate'>
{{#if tableIsEditable}}
  {{> xEditable type="text" success=onSave mode="inline" value=some}}
{{else}}
  {{some}}
{{/if}}
</template>
```

I am happy to work on a pull request for this myself.  Does this sound like something you would be happy to add?  What is your contributions policy on this repo?  Do you need tests written (this repo is a great example of Meteor package testing btw!)?  If so, also happy to add those too.

Looking at the repo code, I think this could be done with a mechanism very similar to that for the cell templates, replacing all uses of `{{getLabel}}` in reactive_table.html with:

```html
  {{#if labelTmpl}}{{#with labelData}}{{> ../labelTmpl}}{{/with}}{{else}}{{getLabel}}{{/if}}
```

The only thing I'm not too sure on is how to set the data context of the header template instance.  There is no 'row' object or array item that applies for the table header itself.  Explicitly setting the data context in the field definition object would work for my use case.

Thanks so much for creating this incredibly useful library!

**Comment by aslagle** [comment]
That would be great, go for it. It sounds useful and consistent with the other options. I don't really have a contributions policy, but I do make sure everything is documented and tested. I usually write the tests myself but I'd be happy to have you do it :)

**Comment by aslagle** [comment]
This is version 0.6.4, thanks!
