### ISSUE TITLE
Adding or displaying columns on reactive reruns of tableSettings does not work

### ISSUE THREAD

**Issue by Waiski** [aslagle/reactive-table#156]
In my app, I use reactive table to display entries that might have a 'problematic' flag on them. The template that contains the table subscribes to the collection in an autorun function and iterates through all the entries, searching if any of them has the problematic flag on. This is strored as a boolean to a ReactiveVar, and this ReactiveVar is used to determine whether to show a 'problem description' column in the table at all:
```javascript
Template.tableContainer.created = function() {
    var that = this;
    this.problems = new ReactiveVar(false);
    this.autorun(function() {
        // Subscription etc here...
        // ....
        var problems = false;
        cursor.forEach(function(item) {
            if (!problems && item.problematic)
                problems = true;
        });
        that.problems.set(problems);
    });
});
Template.tableContainer.helpers({
    tableSettings: function() {
        var fields = { ... };
        if (Template.instance().problems.get())
            fields.unshift({label: 'Problem description', ...});
        return {fields: fields, ....};
    }
});
```
Now, if problematic items are found, then the **last column disappears**. After some considerable debugging effort I *think* I figured out what happens here: As the table settings helper is run the first time, problematic is false (default value), since the items are not loaded yet. After the items are loaded and the autorun has been ran, the table settings helper immediately re-runs, this time adding the problem description column properly. **But** as the reactive table setup function caches the visibleFields-array in the context, it is not updated, even though the fields-array is. Thus **reactively increasing the number of visible fields has no effect on the actual number of fields shown.**

So the culprit, as far as I can tell, are these rows: (reactive_table.js, rows 192 - 198)
```javascript
var visibleFields = [];
_.each(fields, function (field, i) {
    if (!field.hidden || (_.isFunction(field.hidden) && !field.hidden())) {
        visibleFields.push(i);
    }
});
context.visibleFields = (!_.isUndefined(oldContext.visibleFields) && !_.isEmpty(oldContext.visibleFields)) ? oldContext.visibleFields : new ReactiveVar(visibleFields);
```
Where the last row loads visibleFields from cache if it is set and not empty, regardless of its value. I think this could be simply fixed, for example, by comparing the old visible fields with the new value and setting the new value if they differ. **Or did I miss something?**

**Comment by aslagle** [comment]
visibleFields is cached for the showColumnToggles option, which adds a button above the table that lets the user control which columns are displayed. If the user has hidden some columns, they shouldn't show up again when this code re-runs. 

However, showColumnToggles doesn't really work if the fields change - an index in visibleFields could point to a different column. One approach could be to cache the fields as well, and reset visibleFields only if the fields have changed.

**Comment by rjsmith** [comment]
Hi,

I've just encountered this issue in my own application.  I have a button that allows users to add new columns to an existing reactive table.  New columns do get added in the internal data model, but, as @Waiski points out, the `context.visibleFields` array is not re-computed.  In my case, the new column gets inserted in the right place, but the last column disappears.   By turning `showColumnToggle` setting to true, I can see  the 'missing' last column is still known to reactive table, and can make it re-appear by clicking on its name in the toggle pulldown.  Refreshing the browser, forcing the template and the reactive table to re-render makes all the columns appear as expected.
