### ISSUE TITLE
Multiple tables with server-side collections don't work

### ISSUE THREAD

**Issue by aslagle** [aslagle/reactive-table#159]
When you try to render multiple tables with a server-side publication name as the collection, only one of them shows up.

**Comment by javaknight** [comment]
I also see a variant of this

In my setup I have 2 tables on the screen, both using server side pub.

Table 1 has custom filters, and table 2 uses the default filter.

If I activate a filter on table 1, it shows up and starts working, until I navigate away from the page.

**Comment by markus-li** [comment]
I'm seeing this as well, do you have any idea of where this is occurring? If you point me in the right direction I might be able to fix it myself and supply you with the fix, if you don't have the time.

**Comment by aslagle** [comment]
That would be great. It's probably happening because of the _.debounce here: https://github.com/aslagle/reactive-table/blob/master/lib/reactive_table.js#L20

The updateHandle function needs to be debounced when called from an event handler, but not when called during the initial rendering of the tables. Or, each template instance could have its own debounced copy of the function.

**Comment by markus-li** [comment]
I hope you can use my fix, I'm really new to Meteor, started last week, so I hope I didn't overlook something important.

**Comment by aslagle** [comment]
Fixed, thanks @markus-li !
