### ISSUE TITLE
Could adding of column name to TH style be optional?

### ISSUE THREAD

**Issue by justrag** [aslagle/reactive-table#161]
I have a column named 'mark' and it gets highlighted (by Bootstrap CSS), which I don't need. Setting headerClass in settings doesn't help, the 'mark' class is still there. There should be a way to turn off this behaviour.

**Comment by aslagle** [comment]
Sure, the package doesn't use it for anything, so it should be overridden by headerClass.

**Comment by aslagle** [comment]
Is the class on td elements also a problem?

**Comment by justrag** [comment]
Yes.

**Comment by aslagle** [comment]
I'll probably need to add an option to set the td class, then. It complicates the options, but removing the class entirely would mean you'd need to add your own HTML to have a column-specific event, and it wouldn't be backwards-compatible.

**Comment by justrag** [comment]
Yes, the new option is fine.

**Comment by aslagle** [comment]
Done in version 0.6.9. Setting headerClass will replace the default th class, and there's also a cellClass option that will replace the td class.

**Comment by dcusan** [comment]
Sadly this is not working for me, this object in the fields array:

``` javascript
{
  key: "linkId",
  label: "Link",
  tmpl: Template.tableLinks,
  headerClass: 'col-xs-1'
}
```

produces the following table header markup:

![image](https://cloud.githubusercontent.com/assets/5691039/6512119/6be00604-c369-11e4-8a5b-dd4f77c308d5.png)

Or am I missing something?

**Comment by aslagle** [comment]
That should work. Are you sure you've got the latest version of the package?

**Comment by dcusan** [comment]
You were right, solved with a `meteor update`. Thanks!
