### ISSUE TITLE
Security issue, publication is not per user

### ISSUE THREAD

**Issue by illmat** [aslagle/reactive-table#164]
When trying to publish data for specific users, it always uses the same publication for all users.
I've created an example repo with 2 users.
User1 should see the data, user2 should not see the data.
Logins are:
user1@example.com // test1234
user2@example.com // test1234
https://github.com/illmat/reactivteTablePublishBug

Whatever the first publication triggers, everybody else will see.
Steps to reproduce:
- Start the project
- No data shown (ok, anonymus should not see any data)
- login as user1 (not ok, publish is not rerun)
- stay logged in, restart meteor
- data is shown (ok)
- log out
- data is still shown (not ok, publish is not rerun)

You could also use a second browser with user2. 
The first one who triggers the publication makes them visible for all or for noone.

**Comment by aslagle** [comment]
Thanks for catching this, it is a major bug (and the example repo was very helpful).

Should be fixed in version 0.6.8.

**Comment by illmat** [comment]
Thanks alot, works fine now.
