### ISSUE TITLE
Error then sorting

### ISSUE THREAD

**Issue by tanis2000** [aslagle/reactive-table#165]
I noticed that when I try to sort by a column by clicking on the table header, I get the following error in the console, even though the sorting seems to work:

```
Uncaught RangeError: Maximum call stack size exceeded ejson.js:455 
EJSON.clone ejson.js:494
(anonymous function) underscore.js:113
_.each._.forEach ejson.js:493
EJSON.clone ejson.js:494
(anonymous function) underscore.js:113
_.each._.forEach ejson.js:493
...(and so on)...
```

**Comment by aslagle** [comment]
The table doesn't use EJSON, so this is most likely coming from something else - are you using reactive-dict by any chance? #118 was the same error.

**Comment by tanis2000** [comment]
I checked out #118 and you're right, the error is tye same but I'm passing as the collection a cursor coming from a publication. I don't do any transformation on that collection. It's just the Meteor.users one (it does contain lits of fields and subdocuments though.. but the standard one does as well).

**Comment by aslagle** [comment]
The users collection and subdocuments are usually fine, but I haven't tested it thoroughly. Maybe there's some particular subdocument that causes a problem. Do you know what part of the code the error's coming from?

**Comment by tanis2000** [comment]
I tried setting a breakpoint in ejson.js and here's what I found:
https://dl.dropboxusercontent.com/u/3098924/Loading___.png

Apparently something is passing a reactive dictionary to reactive tables, but I'm not explicitly converting anything to a reactive dictionary. 

Inside my router I use the following code:

```js
  Router.route('admin/users', {
    name: 'admin_users',
    template: 'admin_users',
    controller: 'App.Admin.MainController',
    waitOn: function() {
      return Meteor.subscribe('allUsers');
    },
    data: function() {
      var fields = [ 
      {key:'profile.name', label:'Name'}, 
      {key:'emails', label:'emails', tmpl:Template.admin_users_emails}, 
      {key:'createdAt', label:'Signup date'},
      {
        key:'isAdmin', 
        label:'Admin',
        tmpl:Template.admin_users_toggle_admin 
      },
      {
        key:'disabled', 
        label:'Disabled',
        tmpl:Template.admin_users_toggle_disabled 
      },
      {
        key:'is_dead', 
        label:'Dead',
        tmpl:Template.admin_users_toggle_dead 
      },
      ];
      return { items: Meteor.users.find({}), name: 'User', fields: fields, collection: Meteor.users};
    }
  });
```

And the admin_list.js file that you see referenced in the screenshot is just this file:

```js
Template.admin_list.created = function() {
  Session.set('item', undefined);
}

Template.admin_list.helpers({
  name: function() {
    return this.name;
  },
  items: function () {
    return this.items;
  },
  settings: function() {
    return {
      collection: this.items,
      fields: this.fields
    }
  },
  item: function() {
    return Session.get('item');
  },
  collection: function() {
    return this.collection;
  }
});

Template.admin_list.events({
  'click .reactive-table tr': function (event) {
    var item = this;
    Session.set('item', item);
  }
});

AutoForm.hooks({
  updateItemForm: {
    after: {
      update: function(error, result, template) {
        if (!error) {
          Session.set('item', undefined);
        }
      }
    },
    // Called when any operation succeeds, where operation will be
    // "insert", "update", "submit", or the method name.
    onSuccess: function(operation, result, template) {
      Flash.success(operation + ' successful.');
    },

    // Called when any operation fails, where operation will be
    // "validation", "insert", "update", "submit", or the method name.
    onError: function(operation, error, template) {
      Flash.danger(operation + ' completed with error: ' + error);
    }
  }
})
```

As you can see, the `items` passed to reactive tables is just `Meteor.users.find({})`

**Comment by tanis2000** [comment]
Now I can see where the problem is. I'm doing a Session.set() which is creating a ReactiveDict and that's what's complaining. I'd say the issue is sorted out and it's got nothing to do with your awesome package! :)
Thanks for helping out!

**Comment by aslagle** [comment]
Glad you figured it out :)
