### ISSUE TITLE
Filter and sort do not work if using with collection-helpers

### ISSUE THREAD

**Issue by serkandurusoy** [aslagle/reactive-table#173]
I'm using [collection-helpers](https://github.com/dburles/meteor-collection-helpers/) to transfom the collections.

Reactive table does not filter or sort on the columns that display a transformed value.

Eg:

````javascript
Books = new Mongo.Collection('books');
Authors = new Mongo.Collection('authors');

Books.helpers({
  author: function() {
    return Authors.findOne(this.authorId);
  }
});

Authors.helpers({
  fullName: function() {
    return this.firstName + ' ' + this.lastName;
  },
  books: function() {
    return Books.find({ authorId: this._id });
  }
});
````

In this case, I cannot filter / sort on `fullName`

**Comment by serkandurusoy** [comment]
OK, I've hacked around sorting using:

````javascript
fn: function (value, object) { return object.fullName(); }
````

but it does not solve filter :disappointed:

**Comment by Praxie** [comment]
@serkandurusoy, I assume that this will not work as they filter table by changing the subscription.
So you can filter only by document's fields.

**Comment by serkandurusoy** [comment]
But I'm not providing a collection, I'm returning a cursor so the publication and subscription are both done manually on an unrelated part of the codebase.

filtering and sorting are supposed to be client side, unless explicitely set up to work with subscriptions and over the server.

**Comment by aslagle** [comment]
@serkandurusoy, filtering and sorting is done client side, but it's done using a Meteor collection. Sorting uses fn by default and there's a sortByValue option to use the collection instead - maybe filtering should be the same. 

This is the line that does the filtering: https://github.com/aslagle/reactive-table/blob/master/lib/reactive_table.js#L429

**Comment by serkandurusoy** [comment]
Hm, I see then this is normal and not very easy to solve. You are doing an actual find on the collection and those fields are not there until fetched and transformed.

But that makes me wonder why and how sort works since as far as I understand from your code, you are actually sorting on the collection.find so I'm quite puzzled there...

**Comment by serkandurusoy** [comment]
Ah got!!! Yes the fn method vs sortByValue for sort. Yes, that's probably going to solve the problem here as well. In retrospect, this indeed is quite the expected behavior.

You usually end up with calculated values on tables (eg, name + lastname) and your sort/filter may need to depend on that.

Furthermore, the display and the sort may need to be evaluated in different places.

For example, you may be displaying dates in timeago format, but you definitely need to sort by the actual date object.

So as a direction for your package, perhaps you may want to consider implementing

displayFunction
sortFunction
filterFunction

that each return values for what the display/sort/filter should be done against.
