### ISSUE TITLE
Add specific column to dynamic columns

### ISSUE THREAD

**Issue by minafarid** [aslagle/reactive-table#175]
I am displaying the contents of a collection (that I do not know its schema or columns) in a reactive table. Is it possible to add a column (e.g., with a delete button) to that list of dynamic columns. I understand that  I can explicitly specify all column definitions (keys, labels, etc.), but can I keep all the original columns (fields) and add a new one?

**Comment by aslagle** [comment]
No, there's no way to modify the default columns. But all reactive-table is doing to get them is looking up the fields in one element of the collection, and removing _id.

You could use this same line 
```fields = _.without(_.keys(collection.findOne() || {}), '_id');```
and add your extra column definitions to the fields array.

**Comment by minafarid** [comment]
Thank you!
