### ISSUE TITLE
Reactive Table and Google Chrome Translation

### ISSUE THREAD

**Issue by joncursi** [aslagle/reactive-table#183]
I added a reactive table to my template, and now Chrome keeps telling me the page is written in Italian and would like to translate it for me. How can I tell it to stop doing this?

**Comment by aslagle** [comment]
Try this: http://stackoverflow.com/questions/7228972/disable-chrome-translation-bar-on-my-website

**Comment by joncursi** [comment]
Thank you, it seems like the issue I am facing is unrelated to this package.
