### ISSUE TITLE
Server side reactive filtered data set

### ISSUE THREAD

**Issue by rakish** [aslagle/reactive-table#187]
Hello, thanks for all the work you have put into this.

I have a large data set, 5k+ rows. It looks like getting over 1k becomes unusable. Is there a way to set up the table to initially load a subset of the data(maybe grab rows with a field set to "preview" or "show-init"), and then have the client filter field actively pass whatever it contains to the server and receive a reactive filtered data set?

Thanks again

**Comment by rakish** [comment]
I found data-table based solution that is designed for large data sets. Thanks!

**Comment by hanchang** [comment]
Hi @rakish , would you mind sharing what the solution you found was?

**Comment by rakish** [comment]
Hi Hanchang, if you want to work with a large data set, this has been working for me:

https://github.com/aldeed/meteor-tabular
