### ISSUE TITLE
Dumb question

### ISSUE THREAD

**Issue by haveaguess** [aslagle/reactive-table#192]
Is it possible to just use the table with normal data, not collections? Just for easy table rendering

**Comment by tarzak** [comment]
Reactive-table can work with Mongo.collection, Mongo.cursor and array of objects.
Properties of objects will be your columns. But it is better if your objects will have similar properties. Cause reactive-table analyses first one document in an array and builds structure of the table by results of that analysis. Anyway, you can type what fields do you want for your table by filling property "fields" in the settings object.

**Comment by haveaguess** [comment]
Thanks for your time, I'll have a look
