### ISSUE TITLE
Issue with custom filter

### ISSUE THREAD

**Issue by gicat** [aslagle/reactive-table#193]
Hi,

I have used the new feature that allows to define custom filters. I defined filters as follows:
{{> reactiveTableFilter id="jobSearchFilter" label="Search Job" fields=["jobSearch"] }}

Added the filter in settings of reactiveTable (filters: ['jobSearchFilter']).
The filter doesn't filter only on the selected field, but it search in all fields of the table, so is like having default filter that was available before having custom filters. 

Is my configuration correct or am I missing something?

Regards,
Giuseppe

**Comment by tarzak** [comment]
Do you have in your settings object for reactiveTable, property "fields"? Are the filter's "fields" and the "key" in "fields" from reactiveTable settings object similar?

**Comment by gicat** [comment]
Yes, I have fields in my settings. Here follows my settings:
{
	collection: Meteor.Ads.find({approved: 1}, {sort: { lastupdate: -1 }}),
	rowsPerPage: 10,
	showFilter: false,
	filters: ['jobSearchFilter', 'jobOfferFilter', 'cityFilter'],
	fields: [
		{ key: '_id', label: 'key', hidden: true },
		{ key: 'select', label: 'Details', fn: function () { return new Spacebars.SafeString('<button><i class=\'fa fa-search link\'></i></button>'); }},
		{ key: 'jobSearch', label: 'Search'},
		{ key: 'jobOffer', label: 'Offer' },
		{ key: 'city', label: 'Where', tmpl: Template.whereCol },
		{ key: 'dateentered', label: 'Date', tmpl: Template.dateenteredCol, sort: 'descending' }
	]
};

Thanks in advance.
Regards,
Giuseppe

**Comment by tarzak** [comment]
Console is saying something?

**Comment by gicat** [comment]
No, nothing on server console and even on browser console.

**Comment by gicat** [comment]
I have seen your examples, in particular leaderboard example. Modified my code removing field declaration from template, moving it to helper method as in your example, and now it works.
That is from:
{{> reactiveTableFilter id="jobSearchFilter" label="Search Job" fields=["jobSearch"] }}

to 
{{> reactiveTableFilter id="jobSearchFilter" label="Search Job" fields=jobSearchField }}

with jobSearchField declared in template helper as follows:
'jobSearchField': function() {
        return ['jobSearch'];
    }

Maybe there is an issue in the correct evaluation of filter fields in template.

Regards,
Giuseppe

**Comment by aslagle** [comment]
This is a limitation of Spacebars. It doesn't evaluate javascript arrays or objects in template arguments, so you have to define them in a helper or the template's data context instead.

**Comment by gicat** [comment]
I didn't know this issue. Thank you for the explanation.
Regards,
Giuseppe
