### ISSUE TITLE
Style feature for headers and cells etc

### ISSUE THREAD

**Issue by tarzak** [aslagle/reactive-table#196]
Hello! Really awesome package I fell in love! Thank for your job!!

Is this possible to improve your table by adding straight style via style="{{style}}" in the template and something like "headerStyle", "cellStyle" etc for those elements of the table in settings object?! It would be awesome!

I could try to implement it by myself, but I doubt of successful of these mine implementations).
regards tarzak.

**Comment by aslagle** [comment]
Hi, I'm glad you like the package!

There are already options to set classes on these elements (class and rowClass in the main settings, and headerClass and cellClass in fields), so I don't think additional style options are necessary. In most cases you can add the styles you want to CSS classes, and if you need something more complex you can go with a custom template for the cells.

**Comment by tarzak** [comment]
Allright, thank you for your respond. I will think about templates.

But style could be useful for dynamical changes in the table, or when customer (not developer) want to set some css properties manually and does not have access to css files.

Anyway, thanks :).
regards tarzak.
