### ISSUE TITLE
Table won't show, despite data being present

### ISSUE THREAD

**Issue by batjko** [aslagle/reactive-table#197]
Hi there,

I am handing a collection to my call to the reactiveTable spacebars thingy via a helper:

```javascript
        {{> reactiveTable class="table table-bordered table-hover" settings=settings}}
```
And in my settings I have this:
```javascript
  settings: function () {
        return {
            collection: Row,
            rowsPerPage: 10,
            showFilter: true
        };
    }
```
And I can see that the table is getting data, because the pagination shows me that there are five pages, except there is no Table:
![image](https://cloud.githubusercontent.com/assets/7287076/7068540/fb391a12-deca-11e4-9278-27674d5b296a.png)

Any ideas what I need to do differently?

**Comment by aslagle** [comment]
There's probably a javascript error while rendering the rows. Did you see anything in the console?

**Comment by batjko** [comment]
Nope, both the browser console and meteor server console show nothing.

**Comment by aslagle** [comment]
In that case, I think reactive-table isn't able to get any fields from your collection. If you don't pass in fields, it tries to use the keys from the first item in the collection, but maybe it's initially empty or the first item is empty.

**Comment by batjko** [comment]
I do have an array as one of my properties, e.g. something like this:

```json
{
_id: 234453egsdfgsgblabla,
columns: [1,2,3,4,5],
user: "sdfdfsgdfg",
createdAt: somedate
}
```

What are suggested collection structures then?

**Comment by aslagle** [comment]
Arrays are fine, but I'd recommend passing in fields explicitly instead of having reactive-table infer them. You can use fn or a template in the field to format the array for display if you need to.

**Comment by batjko** [comment]
Sorry for the delay I don't get to work on this every day.

Ok, so I think my problem is that I am trying to get a table going which has as data the cells in the columns of my documents.

I.e. my docs have this array inside:
![image](https://cloud.githubusercontent.com/assets/7287076/7111868/29458366-e1bc-11e4-9ffb-82c8ef3c920c.png)

I'd like a table that uses this array in each document as its "row".
So I've tried setting the fields for reactTable explicitly to this columns array where an identifier marks it as the header:

```javascript
settings: function () {
        return {
            collection: Row,
            rowsPerPage: 10,
            showFilter: true,
            fields: TableHeader
        };
    }
```
![image](https://cloud.githubusercontent.com/assets/7287076/7111910/a1040e68-e1bc-11e4-9de1-d8bbe7b46436.png)


But I'm guessing reactTable wants the properties of each document as its fields, right?

Would you say I need to change my model / doc structure?

**Comment by aslagle** [comment]
Yes, reactive-table expects the fields to be properties of the document if you use the defaults. It does seem like a pretty strange doc structure, but if you want to keep it, you can define a custom function in each field to access the value. I think you could probably create this from your table header array, something like:

```
_.map(TableHeader, function (label, index) {
    return {
        key: label, //key won't be used in this case so it could be anything
        label: label,
        fn: (value, object) { return object.columns[index]; }
    };
});
```

**Comment by batjko** [comment]
Ok thanks. 
I think it's best to close this issue, as we have tracked down my problem to the model I am using, and i'll look at maybe changing the document structure to use properties dynamically instead of using that array.

Many thanks for your help @aslagle. Much appreciated. :+1:
