### ISSUE TITLE
Reactive changing of rowsPerPage

### ISSUE THREAD

**Issue by tarzak** [aslagle/reactive-table#198]
Hello again :).

Can you advice me how to programmatically and reactively I can change rowsPerPage property??

For example, I want to store rowsPerPage in some Session variable and dynamically change rowsPerPage property by changing Session variable.

Looking in the code, I found that rowsPerPage changes with some inner methods. Is that true, or I didn't get something?

**Comment by aslagle** [comment]
You're right, it's currently not possible. Since it might have been changed by the end user, it seemed better not to reactively update it. The only thing that might work is to manipulate the rowsPerPage input when the Session variable changes. 

However, this is something I plan to improve very soon :)

**Comment by tarzak** [comment]
Thank you for answer. Would be awesome if you implement it :).

I have tried to change input via jQuery's .val() method, but it has not changed... mb I have to invoke somehow event "changed" after .val().

**Comment by aslagle** [comment]
In version 0.7.3, I've modified rowsPerPage so it can be set to a ReactiveVar. If you change the ReactiveVar, it will update the table. You can use autorun to sync the ReactiveVar with a Session variable - I have an example in the documentation: https://github.com/aslagle/reactive-table#accessing-and-controlling-table-state

**Comment by tarzak** [comment]
Cool! Thank you :) :+1:

**Comment by boboci9** [comment]
Hi, 
I am trying to change the rowsPerPage attribute but I couldn't manage, could you help me out?
https://github.com/aslagle/reactive-table/issues/301

Thanks!
