### ISSUE TITLE
Add action column for button like update and delete

### ISSUE THREAD

**Issue by yozawiratama** [aslagle/reactive-table#199]
I didn't find a way to add action column for button like update and delete per row.
So every row will have update and delete button.
if i click update so it will trigger event
so do delete button too.

how to add that?

**Comment by aslagle** [comment]
I think the best way is to add a new field with a custom template (using [the tmpl option](https://github.com/aslagle/reactive-table#templates)) to render the buttons. The template will have access to the full object for the row and you can add events to it.

**Comment by peterchoo** [comment]
The technique above is what we are using quite well in our application.

**Comment by yozawiratama** [comment]
Wow it works. thanks

**Comment by bhavikbhavsar** [comment]
Can any one share an example of this one ?

**Comment by BeanMc** [comment]
i think exactly anwser is. use html virtual column. 
https://github.com/aslagle/reactive-table#html
ex:
fn: function (value,obj,key) {
                        console.log(value,obj);
                        return new Spacebars.SafeString(`<button onclick="Meteor.call('channel_del','${obj._id}')" class="button btn-danger">del</button>`);
}
