### ISSUE TITLE
data context for templating

### ISSUE THREAD

**Issue by tarzak** [aslagle/reactive-table#201]
Hello again :).
I have another one question.

Is this possible to make tmpl setting be a function like cellClass that will be able to take value & object contexts as parameters?

For example: I can change css classes for cells depending on values which are in. And i want to dynamically place templates depending on values are in too.
Something like: 
```javascript
tmpl: function (value, object) { 
  if (value > 1)
    return Template.bigTemplate;
  else 
    return Template.smallTemplate;
}
```
Thank you.

**Comment by aslagle** [comment]
The template has the object as its data context, so you can create another template that checks the values to determine what to render. It doesn't get the value separately but it's part of the object.

**Comment by tarzak** [comment]
Looks like I've got it! Thank you :).
Awesome package!!
