### ISSUE TITLE
filter on fn function value

### ISSUE THREAD

**Issue by aminjam** [aslagle/reactive-table#207]
Is there a way to enable filter functionality on `fn` function value? It seems like filter only works the real column value not the rendered/displayed value.

**Comment by aslagle** [comment]
No, sorry, there's no way to do it right now.

**Comment by SachaG** [comment]
Just ran into that issue as well. I'll denormalize the field for now, but it would certainly be useful to be able to filter on virtual columns as well. But then again I can imagine it wouldn't be trivial to implement, especially with the pub/sub aspect.

**Comment by mrmowgli** [comment]
Yeah this is a big one for me as well.  I'd be happy if this was client side only, and didn't use the server side publish, in other words storing all of the fn: () return values as a column array and sorting on that.  Some tactics could be dynamically constructing a client local mongo collection and adding these dynamic columns to that, or alternately decorating the collections from a server collection transform.  One thing is certain, when constructing a table with mostly dynamically generated columns, filtering and sorting are meaningless.

**Comment by graemian** [comment]
I worked around this by using a client-side table filter library called List.js (https://listjs.com)
