### ISSUE TITLE
Export feature 

### ISSUE THREAD

**Issue by almogdesign** [aslagle/reactive-table#208]
Wanted to know if there is an export and print feature?

**Comment by aslagle** [comment]
No, I've thought about export but there are a lot of potential interactions with other features that I'm not sure how to handle. For printing, I think it could work decently well to just use the browser's printing, with a customized print stylesheet if necessary.

**Comment by almogdesign** [comment]
Thanks

**Comment by almogdesign** [comment]
Have you thought about doing something simple like a CV export

**Comment by aslagle** [comment]
Even for a CSV export, it's complicated to handle all the possible table options. I think there would need to be separate options for configuring each column for the CSV as well as the table, and some things wouldn't work for server-side collections. I've implemented CSV export for a couple projects and thought about adding it to this package, but it was easier to do it separately.

**Comment by almogdesign** [comment]
Ok thanks
