### ISSUE TITLE
Display field as HTML

### ISSUE THREAD

**Issue by bryankennedy** [aslagle/reactive-table#217]
Is there any way to display a field in the table as actual HTML rather than escaped HTML?

Currently the table displays fields with HTML as escaped strings with the HTML tags un-rendered.

**Comment by aslagle** [comment]
Yes, see https://github.com/aslagle/reactive-table#html

Spacebars will escape HTML for security reasons unless you use SafeString.

**Comment by bryankennedy** [comment]
Ahh thanks. I read that but didn't properly understand. So I can just use this to return the full HTML.

    fn: function (value) {
      return new Spacebars.SafeString(value);
    }

Works great. I appreciate the help.
