### ISSUE TITLE
Using rowClass/cellClass

### ISSUE THREAD

**Issue by frank1340** [aslagle/reactive-table#219]
Hello, 

I had a question.

I am trying to implement a table by which one column has a button that when clicked changes the state of that row, adding a field (did this) and altering the content & /or color of a cell or two, and then clicking the button again would render the original state of that row.

I figured using rowClass and cellClass was the way to do this, but I cannot glean how to do so.  Do you have an example that I can reference?  Thank you.

**Comment by aslagle** [comment]
I don't have any examples of rowClass and cellClass beyond what's in the README, but I think they could work. Clicking the button would need to modify the state of the object in that row, and rowClass and cellClass would need to be functions that checked some field in the object to change the color. They'd rerun reactively when the object changed.

**Comment by frank1340** [comment]
Okay, I believe I understand.  Thank you.

**Comment by frank1340** [comment]
Works well, just as you said, thank you.
