### ISSUE TITLE
Sorting by another method (or hidden table)

### ISSUE THREAD

**Issue by scottyob** [aslagle/reactive-table#224]
Sorting is done by the visible data.  Would be nice to have a way of sorting by the value instead of what's displayed.

An example, my field looks like this:  
fields: [
					{key: 'created_on', label: 'created', fn: function(value, object) { return moment(object.created_on).fromNow() }},
					'request',
					'hostname',
					{key: 'actions', label: 'Actions', tmpl: Template.rancidTasksActions, cellClass: 'col-md-1'},
				]

![network provisioner](https://cloud.githubusercontent.com/assets/1132154/7929085/2bd88314-093d-11e5-9489-2fdfbf96bb39.jpg)

**Comment by ethers** [comment]
In the docs, does this help?
"If you want to sort by the field's original value instead (for example, if you are making a date human-readable), set sortByValue to true on the field object."

**Comment by ethers** [comment]
If that doesn't help, looking at the other issues, may also help.  example: #102

**Comment by scottyob** [comment]
I'm an idiot.. Missed all of that.  Very sorry for wasting your time but this works perfectly :)
