### ISSUE TITLE
pagination at top?

### ISSUE THREAD

**Issue by rschiavi** [aslagle/reactive-table#225]
any chance to style the pagination to put it up top in addition to the per page selection?

**Comment by aslagle** [comment]
I'm not planning to add any options for configuring the order, but you could reposition it with css. In Chrome, adding a wrapper around reactiveTable with `display: flex` and `flex-direction: column` works, with `order: 1` and `order: 2` on the navigation div and the table.

**Comment by rschiavi** [comment]
cool, thanks, that works

**Comment by mymedicalshopper** [comment]
It would be nice if you could have the pagination be at both the top and bottom for when you have a lot of rows and want someone to be able to go back and forth as quickly as possible.

**Comment by 57even** [comment]
+1

It's a really nice project but it definitely needs some layout customization features
