### ISSUE TITLE
sortByValue does not work anymore

### ISSUE THREAD

**Issue by DavidSichau** [aslagle/reactive-table#229]
With the newest release the `sortByValue` parameter for virtual columns does not work anymore.

If `sortByValue` is used the following javascript error is thrown:

    Error: Sorting not supported on Javascript code

How can the old behaviour that in virtual columns the sorting is achieved via the value be restored? This is exspecially useful for dates.

**Comment by aslagle** [comment]
Could you post your fields? It's working in my test but there could be some cases I missed.

**Comment by jasonxeno** [comment]
In 0.8.0, If you don't add sortByValue: true to all the fields that have functions, then sorting is broken, the order of the rows turns seemingly random when clicking a column to sort.

If you add sortByValue: true to all fields with functions, then sorting works again.

The bug appears to have something to do with having a field with a function that has sortByValue: true in one field and then not having sortByValue: true on another field in the same table.

**Comment by aslagle** [comment]
Thanks, I am handling it differently if all the fields with fn also have sortByValue so that narrows it down. 

The main difference in 0.8.0 is that it's sorting with multiple columns, starting with the most recent one you clicked, but actually using all the columns. If they're all sortByValue or don't have fn, I just do it with minimongo, but if any of them are sorted by fn they're all done with _.sortBy.

So there's probably a field that works with a minimongo sort but not _.sortBy. So far I haven't come up with an example of this, is there anything unusual about your fields? It's also possible that the bug is from a column that wasn't being used for sorting before but now is.

**Comment by jasonxeno** [comment]
I got strings, integers, and dates as my data types. Here is the code for the specific table that has this problem (in coffeescript). If I take sortByValue: true out of any of the fields with functions the sorting goes haywire.

```coffeescript
rates_table_settings: ->
    showFilter: no
    showColumnToggles: no
    rowsPerPage: 100
    useFontAwesome: yes
    showNavigation: 'auto'
    group: 'rates_table'
    rowClass: (doc) ->
      shipment = Shipments.findOne doc.shipment_id
      if doc._id is shipment.lowest_rate_id
        return 'success'
    fields: [
      {
        key: "carrier"
        label: "CARRIER"
        sortByValue: true
        fn: (value, object) ->
          html = '<img src="xxxxxxxxxxxxxxxredactedxxxxxxxxxxxxxx' + value + '.png"  style="height: 25px; width: auto;">'
          Spacebars.SafeString(html)
      }
      {
        key: "service_human"
        label: "SERVICE"
      }
      {
        key: "cost_cents.total"
        label: "COST"
        sortByValue: true
        sortOrder: 0
        sortDirection: 1
        fn: (value, object) ->
          cost = accounting.toFixed(value / 100,2)
          cost_split = cost.split "."
          html = '<h3 style="display: inline;">' + cost_split[0] + '</h3><h5 style="display: inline; vertical-align:top;">.' + cost_split[1] + '</h5>'
          html = '<div class="pricing-head pricing-head-active">
                            <h4 style="padding: 5px;"><i>$</i>' + cost_split[0] + '<i>.' + cost_split[1] + '</i>
                          </div>'
          html
          Spacebars.SafeString(html)
      }
      {
        key: "transit"
        label: "TRANSIT"
        sortByValue: true
        fn: (value, object) ->
          switch value
            when 1 then html = value + " day"
            when 0 then html = "N/A"
            else
              html = value + " days"
          Spacebars.SafeString(html)
      }
      {
        key: "delivery"
        label: "ESTIMATED"
        sortByValue: true
        fn: (value, object) ->
          if object.transit > 0
            html = '<i class="fa fa-calendar"></i> ' + moment(value).format("MM/DD/YY")
          else
            html = 'N/A'
          Spacebars.SafeString(html)
      }
      {
        key: "guaranteed"
        label: "GUARANTEED"
        sortByValue: true
        fn: (value, object) ->
          if value?
            html = '<i class="fa fa-calendar"></i> ' + moment(value).format("MM/DD/YY h:mma")
          else
            html = 'N/A'
          Spacebars.SafeString(html)
      }
    ]
```

**Comment by DavidSichau** [comment]
Here are also my fields:


    settings: function () {
        return {
            collection: this,
            rowsPerPage: 10,
            useFontAwesome:true,
            showFilter: true,
            fields: [
                {'key': 'title', label: function() {return TAPi18n.__("_event_title");}},
                {'key': 'room', label: function() {return TAPi18n.__("_event_room");}},
                {'key': 'hint', sortable: false, label: function() {return TAPi18n.__("_event_hint");}},
                {'key': 'start',
                    //sortByValue: true, //TODO fix this
                    sortDirection: 'ascending',
                    label: function() {return TAPi18n.__("_event_start");},
                    fn: function(value, obj) {
                        return obj.startTime();
                    }
                },
                {'key': 'registeredStudents', sortable: false,
                    label: function() {return TAPi18n.__("_event_student_subscription_single");}
                },
                {'key': 'registeredAssis', sortable: false,
                    label: function() {return TAPi18n.__("_event_assi_subscription");}
                }
            ]
        };
    }

where all fields except `start` are strings.

**Comment by aslagle** [comment]
So these are two different bugs.

@DavidSichau I think what's happening with yours is that you have some Javascript code in your collection, probably in one of the fields that has sortable: false, and it wasn't being used for sorting before v0.8.0 but now it is. 

Could you try removing those fields from the table to see if the error goes away? If that's the problem, I think I'll be able to fix it by excluding the sortable: false fields from the sort query, which I probably should have done in the first place.

**Comment by DavidSichau** [comment]
@aslagle I tried to remove the fields with sortable false. However the error still occurs as soon as I use `sortByValue: true` for the field start.

**Comment by aslagle** [comment]
In that case, I'm not sure what the problem is. I haven't been able to reproduce either of these errors. I went ahead and changed the multi-column sort to only use columns the user has selected or the first sortable column as the default. If it doesn't help, I also added an option to disable multi-column sort - set `multiColumnSort: false` in the overall table settings.

**Comment by DavidSichau** [comment]
@aslagle Thanks this works great for me.
