### ISSUE TITLE
How to reference a filter?

### ISSUE THREAD

**Issue by javaknight** [aslagle/reactive-table#232]
I have an issue where I can't reference a filter (or really, I'm not sure how to reference it.)

I am working with HighCharts and I have a bar chart drawn. When the user clicks a bar on the chart, that acts a filter on the table. On the template where I drew the chart, I attached a filter. 

Problem is, in the highcharts library, the click event (http://api.highcharts.com/highcharts#chart.events.click) doesn't give me back a template reference, only an event. 

My problem is I don't know how to reference a filter unless I'm given a template object to which it's attached. So I can't set the filter on the grid.

**Comment by aslagle** [comment]
The filter doesn't need to be attached to a template. You could store it in a variable that's in the scope of both the template and the click event. You would just have to make sure the filter is created before the template's rendered.

**Comment by javaknight** [comment]
thanks! closing.
