### ISSUE TITLE
Table heading color is black - ignoring bootstrap theme - and hard to see on dark backgrounds

### ISSUE THREAD

**Issue by proehlen** [aslagle/reactive-table#241]
Hi thanks for your extremely useful and easy to use package.  

It appears that you are styling the font color for table headings via the .reactive-table .sortable classes rather than allowing the website's theme to do this.  Black column headings are kind of hard to work with on a dark background.

My code to implement your table template:
````
<template name='AdminFeedback'>
    {{#if Template.subscriptionsReady}}    
        {{> reactiveTable collection=feedback}}
    {{else}}
        {{> Loading}}
    {{/if}}
</template>
````
The result:
![image](https://cloud.githubusercontent.com/assets/8384068/8488714/f4d01124-213e-11e5-930c-21dbda2021da.png)

Another table on my website that I've manually created the HTML for showing the bootstrap themes color for table headings:

![image](https://cloud.githubusercontent.com/assets/8384068/8488748/51baaf5c-213f-11e5-95f1-956e14e6fdb4.png)

Where the black heading color in your template is coming from:
![image](https://cloud.githubusercontent.com/assets/8384068/8488796/c8913a24-213f-11e5-9871-278b2535a03b.png)

Where the heading color is derived from in a standard table:
![image](https://cloud.githubusercontent.com/assets/8384068/8488833/1f1d457c-2140-11e5-9ece-15be38bdb3eb.png)

Would it be possible to let the site theme determine the appropriate color for the headings?

**Comment by aslagle** [comment]
Good point, I have no idea why I did that :)

Fixed in v0.8.4
