### ISSUE TITLE
Pagination problems when changing rowsPerPage

### ISSUE THREAD

**Issue by 57even** [aslagle/reactive-table#244]
If I have 11 rows, have rowsPerPage=10, go to page 2, and choose to see 11 rows per page, I will stay at page 2 even though a page 2 doesn't exist.

This is not a big problem when I have showNavigation="always" but if I have showNavigation="auto", the navigation will disappear and I'm on a page without any rows listed.

When changing number of rows per page in the input field, there should probably be a check whether the page exists and if not, the table should go to either the first page or the last existing page.

**Comment by aslagle** [comment]
Fixed in v0.8.6. Thanks!

**Comment by 57even** [comment]
Thank you! :-)

**Comment by 57even** [comment]
Now it seems that `{{#unless noData}}` is damaged or am I doing something wrong? I could use the `noDataTmpl` before but now it does show the table header even when there are no rows. I have also tried making my own template and even if I change

    {{else}}
      {{> noDataTmpl}}
    {{/unless}}

to

    {{else}}
      <p>No data</p>
    {{/unless}}

it has no effect

**Comment by aslagle** [comment]
It still seems to be working for me...
