### ISSUE TITLE
Turn of sorting for entire table

### ISSUE THREAD

**Issue by 57even** [aslagle/reactive-table#253]
Currently, the documentation says "Note: currently there must be at least one sortable column.".

Why can't I completely turn off sorting for the table?

I really like all the features of the package. Therefore, I use the table for many different purposes on my site, but it's not always desirable to have the tables to be completely dynamic, although it's great in most cases :-D

**Comment by aslagle** [comment]
I actually fixed that already but I forgot to update the README. In the latest version, it should work fine to set `sortable: false` on all columns, let me know if you run into any problems with it. I'll update the docs now.

**Comment by aslagle** [comment]
It's removed now, thanks for noticing this :)
