### ISSUE TITLE
Events in reactive table

### ISSUE THREAD

**Issue by 57even** [aslagle/reactive-table#257]
I have a template 

    <template name="templateName">
      {{> reactiveTable collection=collection}}
    </template>

and an event

    Template.templateName.events({
      "click .toggle": function () {
        // do something with _id
      },
    });

but the event is not triggered. I guess this is because I should use `reactiveTable` instead of `templateName` but neither this will work. What can I do to make events work with reactive-table.

**Comment by aslagle** [comment]
Did you try this: https://github.com/aslagle/reactive-table#using-events

**Comment by 57even** [comment]
Now I did :-) Thanks
