### ISSUE TITLE
HTML from a template?

### ISSUE THREAD

**Issue by wizonesolutions** [aslagle/reactive-table#265]
Instead of using `Spacebars.SafeString`, is it possible to use a template in virtual columns? I want to have an Actions column with Edit/Delete links.

**Comment by aslagle** [comment]
There is a tmpl option you can use instead of fn: https://github.com/aslagle/reactive-table#templates

**Comment by wizonesolutions** [comment]
@aslagle Ah! Sorry, I read poorly; the documentation is pretty clear. I appreciate you replying anyway :)
