### ISSUE TITLE
Data disappears on page reload

### ISSUE THREAD

**Issue by orkhanM** [aslagle/reactive-table#266]
It seems like with the latest version the data disappears from the table when the page is refreshed. The only way I found that the data re-appears is by switching to a new tab and refreshing the application on the server end (adding a blank line and saving a file). For some reason it doesn't work when the current tab is the meteor app and the code is refreshed.

**Comment by aslagle** [comment]
It seems to work fine in my examples. Can you share your table publication or any of the settings that might be related?

**Comment by orkhanM** [comment]
Well, I was using the autopublish as well as insecure package, does reactive-table require those be turned off?

**Comment by aslagle** [comment]
Not that I know of - I tried adding autopublish to [this example](https://github.com/aslagle/reactive-table/tree/master/examples/server) and it still worked. If you can share a repo that reproduces the problem I can look into it.

**Comment by orkhanM** [comment]
My template and template helper function pretty much follows the example in the readme:

```
<template name="Table">
  <div class="container">
    {{> reactiveTable collection=stockCollection }}
  </div>
</template>
```
```
Template.Table.helpers({
  stockCollection: function(){
    return StockData.find({},{field:{_id:0}});
    //return StockData.find();
  }
});
```

And the table works seems to work sometimes but only when I refresh the code on the server end. I have one tab open with the table working and one tab open where the table isn't working.

**Comment by orkhanM** [comment]
The documents look like this 

```
{
	"_id" : "bHzXRtMS4LLu5CSrc",
	"symbol" : "AAPL",
	"ask" : "124.61",
	"bid" : "124.53",
	"dividendYield" : "1.70",
	"dividendPerShare" : "2.08",
	"exDividendDate" : "5/7/2015",
	"daysLow" : "123.90",
	"daysHigh" : "125.74"
}
```

**Comment by orkhanM** [comment]
Weird, I seem to be able to consistently get the table to load if I refresh the page and quickly switch to another tab. If I refresh the page while on the tab the table doesn't load or disappears. The table only loads if the tab is in the background.

**Comment by aslagle** [comment]
The problem is that the subscription isn't ready when the table is first rendered, and you're also not specifying the fields so reactive table tries to get them from an document in the collection. Since the collection's initially empty, you get a table with no columns, and the columns don't update when the collection changes - they're only set on the initial load. The easiest workaround would be to pass in the fields argument - it looks like you always have the same columns so they don't need to come from the collection. You could also wait for the subscription to be ready before rendering the table.

**Comment by orkhanM** [comment]
Thanks,  that worked!

**Comment by mizzao** [comment]
This problem is a little misleading if subscriptions are set up without reactive-table being reloaded explicitly afterward; it seems that sometimes the table is broken while other times it works. Might be good to put a note somewhere.

**Comment by aslagle** [comment]
That's true, I'll make it to log something to the console when this happens.
