### ISSUE TITLE
Render callback

### ISSUE THREAD

**Issue by aramk** [aslagle/reactive-table#268]
Is there a way to provide a callback to fire when each document is rendered as a row? I'd like to be able to modify the CSS class on each row once it's rendered based on the doc.

**Comment by aslagle** [comment]
You can probably use the `rowClass` option: https://github.com/aslagle/reactive-table#rowclass-examples

If `rowClass` is a function, it receives the document as an argument and can return a class based on the document.

**Comment by aramk** [comment]
That's awesome, much appreciated!
