### ISSUE TITLE
Get and set currentPage programatically

### ISSUE THREAD

**Issue by pierreozoux** [aslagle/reactive-table#274]
I have a little issue understanding [this](https://github.com/aslagle/reactive-table#accessing-and-controlling-table-state)

the piece of code doesn't make sense for me, but I don't manage to understand how to correct this.

I also saw [that](https://github.com/aslagle/reactive-table/commit/c26230e49c064cb824d8b70da7797ca45b035eec), I tried to reproduce also on my code without success.

So basically I want this because I added a column with a checkbox, and each time we check a check box, the page is coming back to the first page. (you can check here: https://test.tiopapel.press -> join -> resources check one line, go to the second page and check another one, it will go to the first page)
Do you think it is a bug?

If it is not a bug, a workaround for me would be to manage to make work the `{setings: {currentPage: page}}`, but didn't manage.

Would be glad to have your advices!

Thanks!

**Comment by aslagle** [comment]
It does sound like it could be a bug. It would be better to figure out the problem than use currentPage as a workaround. Does checking a box change any of the other table settings or the data in the table? Your app doesn't allow registration so I couldn't see it myself.

**Comment by pierreozoux** [comment]
Sorry, you can now register if you want.

Basically, there is a [reactiveArray](https://github.com/pierreozoux/TioApp/blob/master/client/views/resources/index.js#L5) to save the checked lines.

And then the value of the column is a [function](https://github.com/pierreozoux/TioApp/blob/master/client/views/resources/index.js#L23) that check if the object is inside that array.

So, each time a checkbox is checked, the reactiveArray is changing, and the reactiveTable is reloading. But from what I understand from your code, it should keep the page number.

I really would like to solve the bug myself, but I don't know where to start :)

Thanks for your help!

**Comment by aslagle** [comment]
It's actually this part of the code that's making it go back to the first page: https://github.com/pierreozoux/TioApp/blob/master/client/views/resources/index.js#L70

This changes the filter, and filtering changes the contents of the table so it sends you back to the first page.

**Comment by pierreozoux** [comment]
ok got it! Thanks a lot :) And sorry for bothering :/
