### ISSUE TITLE
Trying to change the rowsPerPage attribute

### ISSUE THREAD

**Issue by boboci9** [aslagle/reactive-table#301]
Hi, 
I am trying to change the rowsPerPage attribute but I couldn't manage it so far. Could you tell me what am I doing wrong?
```
<template name="products">
 {{> reactiveTable collection=products settings=tableSettings class=tableClass}}
 <button id="moreBtn" class="add-product-btn btn btn-info">  More   </button>
</template>
Template.products.created = function () {
	var rowsPerPage = new ReactiveVar(Session.get('rowsPerPage') || 0);
	this.rowsPerPage = rowsPerPage;
	this.autorun(function () {
		Session.set('rowsPerPage', rowsPerPage.get());
	});
}
Template.products.helpers({
	tableSettings:  function () {
	   // if I use console.log here for Template.instance().rowsPerPage.get() the value is changed but the table is not regenerated with more rows
		return {
			fields: [.....],
			filters: ['generalFilter', 'categoryFilter'],
			showNavigation: 'auto',
			rowsPerPage:  Template.instance().rowsPerPage.get(),
			rowClass: function(item) {
				return item._id + '_row';
			}
		};
	},
	tableClass: 'table table-striped table-hover text-primary'
});
Template.products.events({
	"click #moreBtn": function(event, template){
		// not sure what to put here to make it work
               // I tried the following so far
		Template.instance().rowsPerPage.set(20);
		Session.set('rowsPerPage', 20);
	}
})
```
Thank you for your help

**Comment by boboci9** [comment]
I found the issue in https://github.com/aslagle/reactive-table/blob/master/lib/reactive_table.js#L233 where the oldContext is filled with the old value and not the new value I set in the helper's tableSettings function. I took a look at your example in the leaderboard.js file and you set the currentPage in the tableSettings accordingly but the oldContext variable in your reactive_table.js file still contains the old value. I would gladly commit a PR for this issue as well but I'm not sure for what exactly is the oldContext variable used and I didn't want to cause additional issues, for my current version the following solution works:
reactive_table.js line 233
```
if (!_.isUndefined(oldContext.rowsPerPage)) {
        rowsPerPage = oldContext.rowsPerPage;
    } 
    if (this.data.rowsPerPage && this.data.rowsPerPage instanceof ReactiveVar) {
        rowsPerPage = this.data.rowsPerPage;
    } else if (this.data.settings.rowsPerPage && this.data.settings.rowsPerPage instanceof ReactiveVar) {
        rowsPerPage = this.data.settings.rowsPerPage;
    } else {
        rowsPerPage = new ReactiveVar(this.data.rowsPerPage || this.data.settings.rowsPerPage || 10);
    }
```
Let me know what I can do to help.

**Comment by aslagle** [comment]
For rowsPerPage in the tableSettings, you need to use the actual ReactiveVar - `Template.instance().rowsPerPage`. If you pass in the value from get(), it won't update. Sorry for the delay.

 By the way, the reason for using the oldContext is in case you're letting the user change rowsPerPage from the navigation controls - then it keeps the user's manual settings even when other things change.
