### ISSUE TITLE
Why does this sort not work?

### ISSUE THREAD

**Issue by frank1340** [aslagle/reactive-table#304]
Hello,

patientCount is not a stored field in the record.

                { key: 'patientCount', label:'Patients', fn: function(value, object) {
                    return patients.find({practiceId:object._id}).count();
                }},

The numbers are correct but sorting does nothing.

**Comment by frank1340** [comment]
I made a collection helper; it works if I look at the full collection on the client, but not when I publish it from the server.  What am I doing wrong?

**Comment by frank1340** [comment]
practices.helpers({
    patientCount:function() {
        return patients.find({practiceId:this._id}).count();
    }
})

**Comment by aslagle** [comment]
You're not doing anything wrong, but the fn values are only computed on the client, so there's no way to sort by them from the server. If you need to sort that column you might need to store a copy of the patient count in the practice record, sorry.

**Comment by frank1340** [comment]
I see.  I thought I could craft a way around that.  Thank you.
