### ISSUE TITLE
Using TAP:i18n

### ISSUE THREAD

**Issue by rmuratov** [aslagle/reactive-table#311]
In my own project I use [tap:i18n](https://atmospherejs.com/tap/i18n) and don't want one more i18n package as dependency, so I think about reimplementing reactive-table with `tap:i18n` but maybe... 

Aren't there any plans to switch to `tap:i18n` or to add ability to choose? As I can see it has 64.8K downloads against anti's 7.6K, so it is more popular.

**Comment by aslagle** [comment]
There's some discussion of this in #181. I have no problem with having tap:i18n as an option in addition to anti:i18n if anyone wants to figure out how to do it, but I'm not planning to work on it.

**Comment by rmuratov** [comment]
How could i miss it?

For my own needs just [replaced anti:i18n with tap:i18n](https://github.com/rmuratov/reactive-table) and deleted it from dependencies.
