### ISSUE TITLE
Sorting by exact value using tmpl

### ISSUE THREAD

**Issue by rmuratov** [aslagle/reactive-table#314]
Hello. I have those settings:

```coffeescript
settings: ->
  fields: [
    {key: 'level', label: "Level"}
    {key: 'customId', label: "ID", tmpl: Template.makeItLink}
  ]
```

 And `makeItLink` template:

```html
 <template name="makeItLink">
   <a href="#" class="goto">{{newId customId}}</a>
 </template>
 ```

So `newId` is a global helper that returns some value based on `customId` argument.

And the problem is that reactive-table sorts that column by original values.

Is there any way to sort by calculated value? I also tried to set `sortByValue` to `true` but it's only work for virtual columns I guess.

**Comment by aslagle** [comment]
There's no way to sort by a template, but you can use fn and have the function return HTML. There's an example here: https://github.com/aslagle/reactive-table#html

**Comment by rmuratov** [comment]
Initialy it was `fn`, not an option now unfortunately. Thank you anyway.
