### ISSUE TITLE
Custom Button/List for Column Toggles

### ISSUE THREAD

**Issue by ankushsaxena5** [aslagle/reactive-table#317]
Would be nice to have something for column toggles similar to what is allowed for the filters. Where you can create a custom template and place it wherever we want. 

I imagine the template that someone might create would look like this:

```
<template name="CustomColumnToggle">
     <button id="myButton" data-activates="column-list">Toggle Columns</button>
     <div class="column-list" style="display:none;">
           {{#each item}}
               <input type="checkbox" class="{{id}}"></input>
               <label for="{{id}}">{{columnName}}</div>
          {{/each}}
     </div>
</template>
```

**Comment by aslagle** [comment]
It is possible to use your own controls for toggling the columns. You can add an isVisible ReactiveVar to each field, and have a custom template outside the table that sets the vars to true or false to control which columns are displayed.

**Comment by ankushsaxena5** [comment]
Do you mean to the fields definition? Add (for example / testing purposes) setting isVisible: false to one of the fields doesn't seem to do anything

                {   fieldId: 'type', key: 'type', label: 'Type', 
                    fn: function(value){
                        return "Server";
                    },
                    isVisible: false
                },

**Comment by ankushsaxena5** [comment]
Or I see, perhaps it's the "hidden" attribute which needs to be set to a ReactiveVar

**Comment by aslagle** [comment]
It has to be a ReactiveVar in the settings, not a plain boolean - add the meteor package reactive-var to use it.

```
var isVisible = new ReactiveVar(false);

...
{ fieldId: 'type', ...
  isVisible: isVisible
}
```

Once you've put it in the field definition, you can call isVisible.set(true) or isVisible.set(false) from other parts of your code to show or hide the column.

**Comment by ankushsaxena5** [comment]
Okay, I tried this technique but it doesn't seem to toggle the column values. Here is my glimpse of my implementation:

Template.ResourcesList.created = function () {
    this.location = new ReactiveVar(false);
};

Template.ResourcesList.helpers({
    mySettings: function(){
        var currentTenant = new ColorTokens.Tenant(Meteor.user().profile.currentTenant);
        var allResources = currentTenant.getResources();

        return {
            collection: allResources,
            fields: [
                {   
                    fieldId: 'type', 
                    key: 'type', 
                    label: 'Type', 
                    fn: function(value){
                        return "Server";
                    }
                },
                {   
                    fieldId: 'location', 
                    key: 'location', 
                    label: "Location", 
                    tmpl: Template.LocationTemplate, 
                    cellClass: "no-drill",
                    hidden: Template.instance().location.get()
                },
            ],
            showFilter: false,
            filters: ['customFilter'],
            rowsPerPage: 5,
            noDataTmpl: Template.ResourcesNoData,
        };
    },
});

Template.ResourcesList.events({
    'change [data-column-toggle]': function(e, tmpl) {
        console.log(tmpl.location);
        tmpl.location.set(true);
        console.log(tmpl.location);
    },
});


The console log occurs, and changes from false to true, meaning the column should hide. But the location column doesn't get affected

**Comment by ankushsaxena5** [comment]
Looks like all I had to do was change "hidden" to "isVisible", and leave off the .get() from the fields to get it to work. Thanks for pointing me in the right direction!
