### ISSUE TITLE
Sometimes the filter does not initialize?

### ISSUE THREAD

**Issue by keyscores** [aslagle/reactive-table#321]
I'm getting inconsistent results with the built-in filter. 

Sometimes it seems like the filter only works once the table has been interacted with. As if it hasn't initialized.
 
1. Refresh page
2. Type into filter box, without clicking anywhere else on the page
3. No filtering.
4. Click a header to sort.
5. Filter works.

Is there something that needs to be done to have the filter work on render?

**Comment by aslagle** [comment]
It sounds like a bug, but I haven't seen anything like this. It could be related to #194, which I also haven't been able to reproduce. Is there anything unusual about your collection or your setup?

**Comment by keyscores** [comment]
I'm on aslagle:reactive-table 0.8.13 
I've noticed this in a previous app I built in previous meteor  / node versions.
Thanks for the hard work on this component.

**Comment by sirpy** [comment]
try adding  {{#if Template.subscriptionsReady}} to the template rendering the table

**Comment by aslagle** [comment]
I think this is finally fixed - try version 0.8.29!

**Comment by keyscores** [comment]
Yes I can confirm this is fixed now. Sorry for the delay.
