### ISSUE TITLE
Using mulitple filter fields

### ISSUE THREAD

**Issue by KalalauEnterprises** [aslagle/reactive-table#333]
Hi, I'm having a bit of trouble getting multiple fields to work: My code is like this:

<code>
this.filter = new ReactiveTable.Filter('completedItems', ['listId','itemComplete']);
</code>

I've tried multiple ways of setting the filter, ie:
<code>
this.filter.set({listId:listId,itemComplete:"false"});
</code>
and
<code>
this.filter.set([listId,"false"]);
</code>
If I use only one of the fields at a time, they both work fine.
What is the proper way to set the filter for multiple fields?
Thanks so much! Great package!!!

**Comment by aslagle** [comment]
It sounds like you'll need two filters, one for each field.

```
this.filter1 = new ReactiveTable.Filter('listId', ['listId'])
this.filter2 = new ReactiveTable.Filter('completedItems', ['itemComplete'])

this.filter1.set("false")

# in table settings
  filters: [this.filter1, this.filter2]
```

You can have one filter with multiple fields, but that's for using the same filter term to match either one of the fields. It's more useful for something like text search.

**Comment by KalalauEnterprises** [comment]
Thank you so much! That makes perfect sense.
