### ISSUE TITLE
Exact publication using ReactiveTable.publish

### ISSUE THREAD

**Issue by rmuratov** [aslagle/reactive-table#334]
I realized that `ReactiveTable.publish` doesn't actually publishes data in Meteor way:

```coffeescript
ReactiveTable.publish "purchases", ->
  if Roles.userIsInRole @userId, ["admin"]
    return Purchases
  else
    return []
```

Then on the client:

```javascript
Purchases.find().count() //-> 0
```

So, `ReactiveTable.publish` doesn't extend `Meteor.publish`? If so, i think it should be documented. I can prepare PR, if needed.

**Comment by aslagle** [comment]
Right, it uses Meteor.publish but doesn't extend it. It publishes the rows to a special collection that's only accessible inside the reactive-table package. If you want to use your collection directly you'll have to publish it separately as well. What do you think the documentation should say?

**Comment by rmuratov** [comment]
Thank you. Your comment btw is a great explanation. Would be great to have it in docs in some kind of NOTE section :)

**Comment by aslagle** [comment]
I added it down here: https://github.com/aslagle/reactive-table#server-side-pagination-and-filtering-beta

**Comment by rmuratov** [comment]
:+1:

**Comment by tab00** [comment]
Since we can't simply type `Collection.find().fetch()` in the browser console like for normal Meteor subscriptions, what is the best way to check exactly what documents have been subscribed to by ReactiveTable at any time? I want to make sure that server-side pagination is working.

**Comment by aslagle** [comment]
If you set a breakpoint inside the package you can access the collections. Or you might be able to see them with a tool like mongol, I haven't tried it but I think it does include them.
