### ISSUE TITLE
Publish fields option not working

### ISSUE THREAD

**Issue by BackSpaceTech** [aslagle/reactive-table#335]
This doesn't work for me
```  
ReactiveTable.publish("resources-data", Meteor.users, function () {
    return {fields: {password: 0}};
  });
```
but this does
```  
ReactiveTable.publish("resources-data", Meteor.users, function () {
    return {};
  });

**Comment by aslagle** [comment]
The fields option is supposed to be in the fourth argument, and not a function. Third is the selector, which is optional but you'll have to pass in something to use the fourth argument. I think undefined or {} should work. 

Try
```
ReactiveTable.publish("resources-data", Meteor.users, {}, {fields: {password: 0}});
```

**Comment by BackSpaceTech** [comment]
Thanks
