### ISSUE TITLE
Does reactive-table has default style ?

### ISSUE THREAD

**Issue by sharathbangera6** [aslagle/reactive-table#336]
Wanted to know whether reactive-table uses by Bootstrap 3 by default or do i have to install bootstrap 3 manually ? if its installed with reactive-table how do i use it ? I just installed reactive-table and my tables are displayed without any styles. I don't wanted to write any styles. 

How do i make it looks like this ?

http://reactive-table.meteor.com/

**Comment by aslagle** [comment]
Yes, reactive-table includes bootstrap styling by default but you have to add the bootstrap package separately: `meteor add twbs:bootstrap`.
