### ISSUE TITLE
Routing from the Reactive Table

### ISSUE THREAD

**Issue by sharathbangera6** [aslagle/reactive-table#337]
Hi,

I am using FlowRouter for routing and in the home page i am showing the reactiveTable. Inside the / router i am rending the reactive Table, but how do i pass the collection and config of the Reactive Table to the dynamic Template ? 

  var pages = FlowRouter.group({
    prefix: '/students'
  });

  pages.route('/', {
    action: function(){
      BlazeLayout.render('HomePage', {mainPage:'reactiveTable'});
    }
  });

<template name="HomePage">
    <div class="table">
      {{> Template.dynamic template=mainPage}}
    </div>
</template>

Thank You

**Comment by aslagle** [comment]
I would make another template to contain the reactive table and use that as your main page. That template can set up the collection and config.

**Comment by sharathbangera6** [comment]
I did that ... But my table is being shown twice.

  var pages = FlowRouter.group({
    prefix: '/students'
  });

  pages.route('/', {
    action: function(){
      BlazeLayout.render('reactiveTab', {mainPage:'reactiveTable'});
    }
  });

<div class="content">
        {{> reactiveTab}}
 </div>


<template name="reactiveTab">
    <div class="table">
      {{> reactiveTable collection=students settings=tableSettings}}
    </div>
</template>

**Comment by aslagle** [comment]
That's weird. Why do you have mainPage as reactiveTable when you're using reactiveTab? If reactiveTab renders the table you shouldn't need it.

**Comment by sharathbangera6** [comment]
Even after removing the mainPage, it still behaves same. Don't know what wrong i am doing... Anything wrong with how i am subscribing ?
 
if (Meteor.isClient) {
  
  Meteor.subscribe("attendanceRegister");
 
........
pages.route('/', {
  action: function(){
   BlazeLayout.render('reactiveTab');
}
});

}

**Comment by aslagle** [comment]
I don't think it would be the subscription. You must be rendering it somewhere else in addition to calling BlazeLayout.render. Do you have {{> reactiveTab}} somewhere as well? You shouldn't need that, just define the template and then use BlazeLayout to render it.

**Comment by sharathbangera6** [comment]
No. I haven't used it anywhere. you can look into my code once. 
Below is the link of JSfiddle. 

https://jsfiddle.net/dya8aqd0/

**Comment by aslagle** [comment]
In your HTML you should take out the {{>reactiveTab}} in the content div. BlazeLayout adds that in for you so that's why it's there twice.

**Comment by sharathbangera6** [comment]
Thanks alot that works... But one problem here i want to put my reactiveTable inside the container div other, Bootstrap styles  wont be applied. how do i do that ?

**Comment by sharathbangera6** [comment]
Thank you aslagle that works but i have so many doubt, i am not sure whether i can ask all my doubts on whatever code is written right now. Is there any way i can communicate with you on meteor ?
