### ISSUE TITLE
Unexpected token: operator (>)

### ISSUE THREAD

**Issue by SDaron** [aslagle/reactive-table#343]
Hi,

meteor run works perfectly but i've got an error when I try to build with this package:

```
Errors prevented bundling:                    
While minifying app code:                     

/home/laron/.meteor/packages/standard-minifiers/.1.0.2.1bzej1y++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/uglify-js/lib/parse.js:196:18:
Unexpected token: operator (>)
at new JS_Parse_Error
```
Any clue?

**Comment by aslagle** [comment]
Not sure. What version of meteor and what other packages do you have? 

I haven't tried it with cordova, it could be related to that.

**Comment by SDaron** [comment]
How, sorry, the error was due to a small concomitent modification.
I've should have check this before reporting the error.
Thanks for your great package!
