### ISSUE TITLE
How do display a boolean "checkbox" within a column

### ISSUE THREAD

**Issue by lhaig** [aslagle/reactive-table#346]
Hi,

I have a number of fields in my collections that are boolean in nature.
Is there a way to display this better that having true or false show up?

Also how do I enable editing of details within the tables?

**Comment by aslagle** [comment]
You can use a template for a field to display it however you want - the option is `tmpl`. It will get all the fields in its data context, so you'll have to make separate templates for each field. 

There's no built-in support for editing, but you could also create a template with controls for editing a field.

**Comment by tried2call** [comment]
Hello Coders !

I am also using the reactive table to display checkbox results. Try as I may, I am unable to properly understand the connection between the table field (key / label pair) and the database value.

It is encouraging to hear that a template can display a checkbox both checked and unchecked as needed. I am able to display a checkbox in my table, but cannot make the connection to the database. 

Could you supply, or just point me to a sample of such a template ? 
Thanks !

**Comment by aslagle** [comment]
If your database has a key 'checkboxValue' that contains true/false, you should be able to use a template like:

```
<template name="checkbox">
   <input type="checkbox" checked={{checkboxValue}}/>
</template>
```

The template gets the full database item, not just the one value for the field's key, so you use the key 'checkboxValue' to access the value you want in the template.

**Comment by tried2call** [comment]
Thanks Amy !

**Comment by lhaig** [comment]
I am closing this as I no longer use Meteor
