### ISSUE TITLE
fn function does not know which column it is from

### ISSUE THREAD

**Issue by fafournier** [aslagle/reactive-table#355]
I am generating columns definition from a loop. It could be any number of keys when I reach the fn within the definition and the fn is only aware of the value and the object.  

In my program, the value calculated by fn would be calculated differently based on the key for this column. I cannot see a 'clean' way to get the key information within fn to perform the calculations because fn is used within a helper (getField), the context (this) of fn is not actually the configuration object when it is executed. 

I noticed that in "/lib/reactive_table.js" there is
         var value = get(object, key);
         return fn(value, object);

just returning 
         return fn(value, object, key);
instead would sort my problem and still maintain full backward compatibility. 

I will submit a PR soon. The issue is just for reference. (And hopefully it will be understandable...ish...)

**Comment by semikolon** [comment]
:smiley: Thanks for this, very timely, just started using reactive-table and had the same problem.

**Comment by fafournier** [comment]
Happy to help! I went month with a dirty workaround: fn: new Function('value', 'object', ' return DataProcessing.tablefn(value, object, "'+column._id+'")');

But it was time to let it go when adding the browser-policy settings: BrowserPolicy.content.disallowEval(); :-D
