### ISSUE TITLE
Expandable row

### ISSUE THREAD

**Issue by oscarcalvo** [aslagle/reactive-table#365]
Hello, any news about support to expandable rows? or may an advice about how can I get it quickly.

I have seen this but looks like you have discharged it :https://github.com/aslagle/reactive-table/pull/176

Thanks

**Comment by aslagle** [comment]
Hi, sorry I never got around to what I said in that pr. I don't really want to add an option specifically for this case, but I haven't had time to come up with something more general. Unfortunately I don't think there's any way to get it quickly since it requires modifying the table's html.

**Comment by datanotion** [comment]
@oscarcalvo Oscar, you could consider doing it this way:  https://github.com/aslagle/reactive-table/pull/296 until there is an officially supported option.  I know that the gentleman that wrote it is planning on eventually writing it as a tmpl as @aslagle suggested, but it's an option for now (I'm using it).

**Comment by oscarcalvo** [comment]
thanks @datanotion

**Comment by U54** [comment]
+1 for expandable rows become an official feature, this would be very useful in many situations

**Comment by ClarenceL** [comment]
I've added a new pull request

You can try out the code here: https://github.com/ClarenceL/reactive-table/tree/feature-child-tmpl

It's pretty simple, on the column you want the expand button, for the fields item, add the setting `expandButton: true`

Then add to the root settings object  `
children: {
        tmpl: Template."your template name"
}`

See the added readme CHILD_TABLE_README.md for more details

**Comment by mwkrieger** [comment]
Hey there. I'm just wondering if this branch would be merged at some point. @ClarenceL, I've tried to implement this, but can't get the child row(s) to show on click. 

I'm not sure if I'm missing something or not..
