### ISSUE TITLE
too much for my brain, please help putting this array into table

### ISSUE THREAD

**Issue by Laurentiu-Andronache** [aslagle/reactive-table#370]
I have this local collection:
```
global.emptyOdds = {
  asOriginalInput: '',
  asPercentage: '',
  asExact: null,
  asTruthier: null,
  asTrue: null,
};

global.startNewCheck = () => ChecksCollection.insert({
  oddsChecked: [emptyOdds, emptyOdds],
  oddsAverages: [emptyOdds, emptyOdds],
});
```

As the app is used, the current emptyOdds inside ChecksCollection are modified and more objects are added into the oddsChecked and oddsAverages arrays or existing ones are removed (these arrays always have the same length).

I'm only capable of using this code in order to display data that interests me from the first object of each array:
```
  reactiveTableSettings: function () {
    return {
      collection: ChecksCollection.findOne(),
      showFilter: false,
      sortable: false,
      multiColumnSort: false,
      showNavigation: 'auto',
      fields: [
        {key: 'oddsChecked.0.asPercentage', label: 'Implied Probability'},
        {key: 'oddsChecked.0.asTruthier', label: 'Truthier Probability', fn: (value) => value ? showAsPercentage(value) : ''},
        {key: 'oddsChecked.0.asTrue', label: 'True Probability', fn: (value) => value ? showAsPercentage(value) : ''},
        {key: 'oddsAverages.0.asPercentage', label: 'Average Probability'}      
      ]
    }
  }
```

I would like to be able to display the rest of the rows as well, however many they might be. Can you please help?

**Comment by aslagle** [comment]
Not sure I understand what you're trying to do, but if you only insert into ChecksCollection once, what about using the oddsChecked array as the reactive table collection setting instead of ChecksCollection?

```
collection: ChecksCollection.findOne().oddsChecked
```

And the field keys would be 'asPercentage', 'asTruthier', 'asTrue' without the array index.

**Comment by Laurentiu-Andronache** [comment]
Your solution works:
```
  reactiveTableSettings: function () {
    return {
      collection: ChecksCollection.findOne().oddsChecked,
      showFilter: false,
      sortable: false,
      multiColumnSort: false,
      showNavigation: 'auto',
      fields: [
        {key: 'asPercentage', label: 'Implied Probability'},
        {key: 'asTruthier', label: 'Truthier Probability', fn: (value) => value ? showAsPercentage(value) : ''},
        {key: 'asTrue', label: 'True Probability', fn: (value) => value ? showAsPercentage(value) : ''}
      ]
    }
  }
```

I updated the second code sample from the first post to be more specific. How do I add another column that has the ChecksCollection.findOne().oddsAverages source? Both these sources have the same number of objects...

**Comment by aslagle** [comment]
I think the easiest way is to combine the sources into one array for the table.

This will make an array of arrays, with each array having oddsChecked at 0 and oddsAverages at 1, so you can use them in the same row:
```
var check = ChecksCollection.findOne();
var collection = _.zip(check.oddsChecked, check.oddsAverages);

return {
      collection: collection,
      showFilter: false,
      sortable: false,
      multiColumnSort: false,
      showNavigation: 'auto',
      fields: [
        {key: '0.asPercentage', label: 'Implied Probability'},
        {key: '0.asTruthier', label: 'Truthier Probability', fn: (value) => value ? showAsPercentage(value) : ''},
        {key: '0.asTrue', label: 'True Probability', fn: (value) => value ? showAsPercentage(value) : ''},
        {key: '1.asPercentage', label: 'Average Probability'}
      ]
};
```

**Comment by Laurentiu-Andronache** [comment]
Hi. This has worked perfectly. As a small token of appreciation, let me know (by following my profile on Github) if you'll want this [https://productmonth.com/march-2016](book for free: https://ProductMonth.com/march-2016). If you do, I'll email it to you after it gets past the editor.
