### ISSUE TITLE
Getting field to show inside templates

### ISSUE THREAD

**Issue by oscarcalvo** [aslagle/reactive-table#371]
Hi,
I want to have generic templates, so I can render tables where I reuse the same templates for diferent fields or tables. So I would like to say
```
fields:[
{key:'createdAt', label:'....', tmpl:Template.dateTemplate}
{key:'updatet', label:'....'}
]
```
`<template name="dateTemplate">
<span>???? (I would like something like {this[key]})</span>
</template>`

The problem is that I dont know how can I get the field I have to render so I can show it where I am writing ????

Do you know? thanks.

**Comment by aslagle** [comment]
The field key is one level up in the template data context but it's kind of ugly to access it. One way is to write a helper in your template that returns `this[Template.parentData(1).key]` and call the helper where you have ????.

**Comment by oscarcalvo** [comment]
its perfect @aslagle , thanks.
