### ISSUE TITLE
Sorting on Virtual Columns Always Using Value and not Computed

### ISSUE THREAD

**Issue by kevinterrobang** [aslagle/reactive-table#375]
I have a reactive table that is displaying a date. The value is passed as a string, where 10 comes before 9. I am using a function to format the date into a displayable and sortable format where 09 comes before 10. However, it seems no matter what the virtual column does to the string, the original data value string is being used for the sort. I've even tried explicitly setting the sortByValue to false.

I am using aslagle:reactive-table@0.8.28

HTML
```
{{> reactiveTable collection='dashboard/summary' fields=fields}}
```
javascript
```
Template.adminDashboard.helpers({
  fields: function () {
    return [{
      key: 'summaryDate',
      label: 'Date',
      sortDirection: 'descending',
      sortByValue: false,
      fn: function (date) {
        return moment(new Date(date)).format('YYYY-MM-DD')
      }
    }];
  }
});
```
actual output
```
Date   ▼
2016-03-09
2016-03-08
2016-03-07
2016-03-05
2016-03-04
2016-03-03
2016-03-28
2016-03-26
2016-03-25
2016-03-24
```
expected output
```
Date   ▼
2016-03-28
2016-03-26
2016-03-25
2016-03-24
2016-03-23
2016-03-22
2016-03-21
2016-03-20
2016-03-19
2016-03-18
```

**Comment by aslagle** [comment]
The sortByValue option unfortunately only works client-side. If you're using ReactiveTable.publish, all the sorting happens on the server. Even if it had the display function on the server it would be slow to compute it on every document. You could store the formatted dates in the collection, or if your collection is small enough you could publish the whole collection so the sorting could happen on the client.

**Comment by kevinterrobang** [comment]
ah that makes sense.

... oh wow i'm storing that "date" as a string because i didn't need the time. will just have to format it correctly, as you suggested. sorry, just a case of the right hand not talking to the left. thanks for your time =)
