### ISSUE TITLE
Switch collection filter with tabs breaks filter

### ISSUE THREAD

**Issue by ivan133** [aslagle/reactive-table#379]
I have a problem, I have reactive-table and 2 tabs.
Then I click on tabs I reactive change the collection that goes to collection in template (the classifier helper).

`{{> reactiveTable collection=classifier settings=tableSettings}}`

The problem is that autofilter works only on first render.

**Is that expected behavior?** 

I've made simple example to demonstrate this behavior 
https://github.com/ivan133/reactive-table-test

How to reproduce:
1. click on 1. You should see "test1"
2. Type in filter "sadsad", the "test1" row goes away
3. click on 1. You should see "test2"
4. Type in filter "sadsad", the "test2" remains. In fact autofilter does not work anymore.

**Comment by aslagle** [comment]
It should be fixed now, try version 0.8.29 :)

**Comment by ivan133** [comment]
Yep this works!
