### ISSUE TITLE
multi user

### ISSUE THREAD

**Issue by interfaith** [aslagle/reactive-table#380]
with each user is a new reactive-table needed ?
same with aldeed when each user has varying columns/collections

**Comment by aslagle** [comment]
It's possible to have different columns and collections for each user - you can use the user id in template helpers to determine the fields or collection for the reactive table settings, and on the server you can use the user id in function you pass to ReactiveTable.publish. Not sure what the question is exactly?

**Comment by interfaith** [comment]
Yes as you indicated each user will push queries of  various colums to the
output collection . The reactive
table does publish the needed columns and rows for a given query ID .
However
for some reason it is SLOW when populating a few hundred rows ?
Reactive-table is much more flexible than meteor-tabular for multiple users
with various columns.
Though slower. :(


On Sun, Apr 17, 2016 at 7:52 AM, Amy Slagle <notifications@github.com>
wrote:

> It's possible to have different columns and collections for each user -
> you can use the user id in template helpers to determine the fields or
> collection for the reactive table settings, and on the server you can use
> the user id in function you pass to ReactiveTable.publish. Not sure what
> the question is exactly?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/aslagle/reactive-table/issues/380#issuecomment-211038145>
>



-- 
-----
Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D

**Comment by interfaith** [comment]
With 2 users , the 2nd user display affects/blanks the 1st. A client side
headers[] is found
via a Meteor.call. Any single user call works.

On Sun, Apr 17, 2016 at 9:23 AM, Mark Spowage <spowage@gmail.com> wrote:

> Yes as you indicated each user will push queries of  various colums to the
> output collection . The reactive
> table does publish the needed columns and rows for a given query ID .
> However
> for some reason it is SLOW when populating a few hundred rows ?
> Reactive-table is much more flexible than meteor-tabular for multiple
> users with various columns.
> Though slower. :(
>
>
> On Sun, Apr 17, 2016 at 7:52 AM, Amy Slagle <notifications@github.com>
> wrote:
>
>> It's possible to have different columns and collections for each user -
>> you can use the user id in template helpers to determine the fields or
>> collection for the reactive table settings, and on the server you can use
>> the user id in function you pass to ReactiveTable.publish. Not sure what
>> the question is exactly?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/aslagle/reactive-table/issues/380#issuecomment-211038145>
>>
>
>
>
> --
> -----
> Fight back spam! Download the Blue Frog.
> http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D
>



-- 
-----
Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D

**Comment by interfaith** [comment]
A 2nd browser for the 2nd user did work ok. Two from a single chrome
window, 2 tabs failed.
So I guess reactive-table is working for several users each with a set of
columns. No common client/server code needed.

On Sun, Apr 17, 2016 at 9:53 AM, Mark Spowage <spowage@gmail.com> wrote:

> With 2 users , the 2nd user display affects/blanks the 1st. A client side
> headers[] is found
> via a Meteor.call. Any single user call works.
>
> On Sun, Apr 17, 2016 at 9:23 AM, Mark Spowage <spowage@gmail.com> wrote:
>
>> Yes as you indicated each user will push queries of  various colums to
>> the output collection . The reactive
>> table does publish the needed columns and rows for a given query ID .
>> However
>> for some reason it is SLOW when populating a few hundred rows ?
>> Reactive-table is much more flexible than meteor-tabular for multiple
>> users with various columns.
>> Though slower. :(
>>
>>
>> On Sun, Apr 17, 2016 at 7:52 AM, Amy Slagle <notifications@github.com>
>> wrote:
>>
>>> It's possible to have different columns and collections for each user -
>>> you can use the user id in template helpers to determine the fields or
>>> collection for the reactive table settings, and on the server you can use
>>> the user id in function you pass to ReactiveTable.publish. Not sure what
>>> the question is exactly?
>>>
>>> —
>>> You are receiving this because you authored the thread.
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/aslagle/reactive-table/issues/380#issuecomment-211038145>
>>>
>>
>>
>>
>> --
>> -----
>> Fight back spam! Download the Blue Frog.
>> http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D
>>
>
>
>
> --
> -----
> Fight back spam! Download the Blue Frog.
> http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D
>



-- 
-----
Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D

**Comment by interfaith** [comment]
Just to switch pages when 10k rows are loaded takes about 2 seconds in
chrome.
My guess is meteor-tabular does some server side paging , so multi user is
sacrificed.

Some trade off needed between server/client side rendering.

Here no "reactive" table action is not needed initially.

A "PAGE" button could be used to grab 1k row pages so the client side
has a 1k row data set.



On Sun, Apr 17, 2016 at 9:57 AM, Mark Spowage <spowage@gmail.com> wrote:

> A 2nd browser for the 2nd user did work ok. Two from a single chrome
> window, 2 tabs failed.
> So I guess reactive-table is working for several users each with a set of
> columns. No common client/server code needed.
>
> On Sun, Apr 17, 2016 at 9:53 AM, Mark Spowage <spowage@gmail.com> wrote:
>
>> With 2 users , the 2nd user display affects/blanks the 1st. A client side
>> headers[] is found
>> via a Meteor.call. Any single user call works.
>>
>> On Sun, Apr 17, 2016 at 9:23 AM, Mark Spowage <spowage@gmail.com> wrote:
>>
>>> Yes as you indicated each user will push queries of  various colums to
>>> the output collection . The reactive
>>> table does publish the needed columns and rows for a given query ID .
>>> However
>>> for some reason it is SLOW when populating a few hundred rows ?
>>> Reactive-table is much more flexible than meteor-tabular for multiple
>>> users with various columns.
>>> Though slower. :(
>>>
>>>
>>> On Sun, Apr 17, 2016 at 7:52 AM, Amy Slagle <notifications@github.com>
>>> wrote:
>>>
>>>> It's possible to have different columns and collections for each user -
>>>> you can use the user id in template helpers to determine the fields or
>>>> collection for the reactive table settings, and on the server you can use
>>>> the user id in function you pass to ReactiveTable.publish. Not sure what
>>>> the question is exactly?
>>>>
>>>> —
>>>> You are receiving this because you authored the thread.
>>>> Reply to this email directly or view it on GitHub
>>>> <https://github.com/aslagle/reactive-table/issues/380#issuecomment-211038145>
>>>>
>>>
>>>
>>>
>>> --
>>> -----
>>> Fight back spam! Download the Blue Frog.
>>> http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D
>>>
>>
>>
>>
>> --
>> -----
>> Fight back spam! Download the Blue Frog.
>> http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D
>>
>
>
>
> --
> -----
> Fight back spam! Download the Blue Frog.
> http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D
>



-- 
-----
Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D

**Comment by aslagle** [comment]
Did you try the reactive table server side publishing?

https://github.com/aslagle/reactive-table#server-side-pagination-and-filtering-beta

**Comment by interfaith** [comment]
Ok so any start /end row markers can be saved in a queryId collection to
guide
the pagination as needed, super !

On Sun, Apr 17, 2016 at 5:31 PM, Amy Slagle <notifications@github.com>
wrote:

> Did you try the reactive table server side publishing?
>
>
> https://github.com/aslagle/reactive-table#server-side-pagination-and-filtering-beta
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/aslagle/reactive-table/issues/380#issuecomment-211138868>
>



-- 
-----
Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D

**Comment by interfaith** [comment]
Are "." dots allowed in the column name ? others do not :(

On Sun, Apr 17, 2016 at 5:31 PM, Amy Slagle <notifications@github.com>
wrote:

> Did you try the reactive table server side publishing?
>
>
> https://github.com/aslagle/reactive-table#server-side-pagination-and-filtering-beta
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/aslagle/reactive-table/issues/380#issuecomment-211138868>
>



-- 
-----
Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D

**Comment by aslagle** [comment]
Dots are used for accessing a nested object in mongo. You can have a separate 'key' and 'label' if you just want to display a column header with a dot.

**Comment by interfaith** [comment]
Any example to reference for this ?

For some weird reason I need to subscribe else nothing happens. Only the
1st argument
in subscribe is taken (queryId) and that works.

The new pagination code below, Can all fields be taken by default ? Without
a client subscribe
nothing happens.

xqueryData = function()
{
  var mqid =  QueryRecord.findOne({userId: this.userId});
  console.log("FINDTHE QUERY RECORD " + mqid._id);
//add startrow stoprow to paginate
  console.log("qcount is " + queryData.find({sys_queryId:
mqid._id}).count());
  return  {sys_queryId: mqid._id};
//return  queryData.find({sys_queryId: mqid._id},{rowId: {$gt:
mqid.startrow,$lt: mqid.stoprow});

}

//ReactiveTable.publish("joinquery",queryData,xqueryData,{fields:
{sys_queryId: 1,sys_user: 1,rowId: 1,t1a1: 1}});

ReactiveTable.publish("joinquery",queryData,xqueryData);

 {{#if selected_query_data}}

  {{> reactiveTable collection="joinquery"}}

  {{/if}}


button helper
query_list.js:434 READY NOW
query_list.js:436 find ALL DATA done1
query_list.js:182 got selected query data change 3S2hxGYxxjFaBBczu
aslagle_reactive-table.js?hash=5ef073d…:915 reactiveTable error: fields
option is required with server-side publications


On Sun, Apr 17, 2016 at 7:03 PM, Amy Slagle <notifications@github.com>
wrote:

> Dots are used for accessing a nested object in mongo. You can have a
> separate 'key' and 'label' if you just want to display a column header with
> a dot.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/aslagle/reactive-table/issues/380#issuecomment-211153317>
>



-- 
-----
Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D

**Comment by interfaith** [comment]
no need for server side pagination, as client side subscribe can request
just the needed rows to avoid waiting.

On Mon, Apr 18, 2016 at 10:16 AM, Mark Spowage <spowage@gmail.com> wrote:

> Any example to reference for this ?
>
> For some weird reason I need to subscribe else nothing happens. Only the
> 1st argument
> in subscribe is taken (queryId) and that works.
>
> The new pagination code below, Can all fields be taken by default ?
> Without a client subscribe
> nothing happens.
>
> xqueryData = function()
> {
>   var mqid =  QueryRecord.findOne({userId: this.userId});
>   console.log("FINDTHE QUERY RECORD " + mqid._id);
> //add startrow stoprow to paginate
>   console.log("qcount is " + queryData.find({sys_queryId:
> mqid._id}).count());
>   return  {sys_queryId: mqid._id};
> //return  queryData.find({sys_queryId: mqid._id},{rowId: {$gt:
> mqid.startrow,$lt: mqid.stoprow});
>
> }
>
> //ReactiveTable.publish("joinquery",queryData,xqueryData,{fields:
> {sys_queryId: 1,sys_user: 1,rowId: 1,t1a1: 1}});
>
> ReactiveTable.publish("joinquery",queryData,xqueryData);
>
>  {{#if selected_query_data}}
>
>   {{> reactiveTable collection="joinquery"}}
>
>   {{/if}}
>
>
> button helper
> query_list.js:434 READY NOW
> query_list.js:436 find ALL DATA done1
> query_list.js:182 got selected query data change 3S2hxGYxxjFaBBczu
> aslagle_reactive-table.js?hash=5ef073d…:915 reactiveTable error: fields
> option is required with server-side publications
>
>
> On Sun, Apr 17, 2016 at 7:03 PM, Amy Slagle <notifications@github.com>
> wrote:
>
>> Dots are used for accessing a nested object in mongo. You can have a
>> separate 'key' and 'label' if you just want to display a column header with
>> a dot.
>>
>> —
>> You are receiving this because you modified the open/close state.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/aslagle/reactive-table/issues/380#issuecomment-211153317>
>>
>
>
>
> --
> -----
> Fight back spam! Download the Blue Frog.
> http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D
>



-- 
-----
Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D

**Comment by interfaith** [comment]
super !!

 reactive ok ! when the collection changes the display updates new data set
to view.

 return {
            collection: queryData.find({rowId: {$gt:
Session.get("startrow"),$lt: Session.get("stoprow") }}).fetch(),
            rowsPerPage: 10,
            showFilter: true,
            fields: headers
            };

On Mon, Apr 18, 2016 at 11:29 AM, Mark Spowage <spowage@gmail.com> wrote:

> no need for server side pagination, as client side subscribe can request
> just the needed rows to avoid waiting.
>
> On Mon, Apr 18, 2016 at 10:16 AM, Mark Spowage <spowage@gmail.com> wrote:
>
>> Any example to reference for this ?
>>
>> For some weird reason I need to subscribe else nothing happens. Only the
>> 1st argument
>> in subscribe is taken (queryId) and that works.
>>
>> The new pagination code below, Can all fields be taken by default ?
>> Without a client subscribe
>> nothing happens.
>>
>> xqueryData = function()
>> {
>>   var mqid =  QueryRecord.findOne({userId: this.userId});
>>   console.log("FINDTHE QUERY RECORD " + mqid._id);
>> //add startrow stoprow to paginate
>>   console.log("qcount is " + queryData.find({sys_queryId:
>> mqid._id}).count());
>>   return  {sys_queryId: mqid._id};
>> //return  queryData.find({sys_queryId: mqid._id},{rowId: {$gt:
>> mqid.startrow,$lt: mqid.stoprow});
>>
>> }
>>
>> //ReactiveTable.publish("joinquery",queryData,xqueryData,{fields:
>> {sys_queryId: 1,sys_user: 1,rowId: 1,t1a1: 1}});
>>
>> ReactiveTable.publish("joinquery",queryData,xqueryData);
>>
>>  {{#if selected_query_data}}
>>
>>   {{> reactiveTable collection="joinquery"}}
>>
>>   {{/if}}
>>
>>
>> button helper
>> query_list.js:434 READY NOW
>> query_list.js:436 find ALL DATA done1
>> query_list.js:182 got selected query data change 3S2hxGYxxjFaBBczu
>> aslagle_reactive-table.js?hash=5ef073d…:915 reactiveTable error: fields
>> option is required with server-side publications
>>
>>
>> On Sun, Apr 17, 2016 at 7:03 PM, Amy Slagle <notifications@github.com>
>> wrote:
>>
>>> Dots are used for accessing a nested object in mongo. You can have a
>>> separate 'key' and 'label' if you just want to display a column header with
>>> a dot.
>>>
>>> —
>>> You are receiving this because you modified the open/close state.
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/aslagle/reactive-table/issues/380#issuecomment-211153317>
>>>
>>
>>
>>
>> --
>> -----
>> Fight back spam! Download the Blue Frog.
>> http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D
>>
>
>
>
> --
> -----
> Fight back spam! Download the Blue Frog.
> http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D
>



-- 
-----
Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D

**Comment by aslagle** [comment]
Glad you got it to work! If you manage the pagination and filtering yourself, you don't need ReactiveTable.publish and you can display whatever data you want.

**Comment by interfaith** [comment]
so far so good, see bjoindata.com login bjoindemo pwd bjoindemo

run the select all query.

for some reason it takes a second or 2 to render when the window is more
than 400 rows.

after the publish is done and the subscription is ready

there is a way to know when the table is fully rendered ? using template
rendered ?

anyway we'll stay with reactive-table as it allows multi users.

i should push an 'example' to github for others trying to do table displays.


On Mon, Apr 18, 2016 at 6:17 PM, Amy Slagle <notifications@github.com>
wrote:

> Glad you got it to work! If you manage the pagination and filtering
> yourself, you don't need ReactiveTable.publish and you can display whatever
> data you want.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/aslagle/reactive-table/issues/380#issuecomment-211669008>
>



-- 
-----
Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D

**Comment by interfaith** [comment]
The client side subscribe takes time to get "ready" a few seconds for just
100 rows !
Should all client side records be erased before the window is moved ?

On Tue, Apr 19, 2016 at 9:13 AM, Mark Spowage <spowage@gmail.com> wrote:

> so far so good, see bjoindata.com login bjoindemo pwd bjoindemo
>
> run the select all query.
>
> for some reason it takes a second or 2 to render when the window is more
> than 400 rows.
>
> after the publish is done and the subscription is ready
>
> there is a way to know when the table is fully rendered ? using template
> rendered ?
>
> anyway we'll stay with reactive-table as it allows multi users.
>
> i should push an 'example' to github for others trying to do table
> displays.
>
>
> On Mon, Apr 18, 2016 at 6:17 PM, Amy Slagle <notifications@github.com>
> wrote:
>
>> Glad you got it to work! If you manage the pagination and filtering
>> yourself, you don't need ReactiveTable.publish and you can display whatever
>> data you want.
>>
>> —
>> You are receiving this because you modified the open/close state.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/aslagle/reactive-table/issues/380#issuecomment-211669008>
>>
>
>
>
> --
> -----
> Fight back spam! Download the Blue Frog.
> http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D
>



-- 
-----
Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D

**Comment by aslagle** [comment]
I think it looks better to display the old data in the table until new data is ready, but in some apps it might be confusing. 

If I remember correctly Template.rendered gets called when the table is put into the DOM, but not when it's updated with more data, so it might not work for you. I'm not sure if there's a way to know when all the data has been rendered. Usually knowing when the subscription is ready is enough.

If you do put your example on github please share the link :)

**Comment by interfaith** [comment]
bjoindata.com seems to be ok with a window of 100 rows and page buttons for
fine tuning.
we'll go with this.

the trick to avoid delay is to grab an array to avoid minimongo I/O

trial and error rules.

On Tue, Apr 19, 2016 at 11:23 AM, Mark Spowage <spowage@gmail.com> wrote:

> The client side subscribe takes time to get "ready" a few seconds for just
> 100 rows !
> Should all client side records be erased before the window is moved ?
>
> On Tue, Apr 19, 2016 at 9:13 AM, Mark Spowage <spowage@gmail.com> wrote:
>
>> so far so good, see bjoindata.com login bjoindemo pwd bjoindemo
>>
>> run the select all query.
>>
>> for some reason it takes a second or 2 to render when the window is more
>> than 400 rows.
>>
>> after the publish is done and the subscription is ready
>>
>> there is a way to know when the table is fully rendered ? using template
>> rendered ?
>>
>> anyway we'll stay with reactive-table as it allows multi users.
>>
>> i should push an 'example' to github for others trying to do table
>> displays.
>>
>>
>> On Mon, Apr 18, 2016 at 6:17 PM, Amy Slagle <notifications@github.com>
>> wrote:
>>
>>> Glad you got it to work! If you manage the pagination and filtering
>>> yourself, you don't need ReactiveTable.publish and you can display whatever
>>> data you want.
>>>
>>> —
>>> You are receiving this because you modified the open/close state.
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/aslagle/reactive-table/issues/380#issuecomment-211669008>
>>>
>>
>>
>>
>> --
>> -----
>> Fight back spam! Download the Blue Frog.
>> http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D
>>
>
>
>
> --
> -----
> Fight back spam! Download the Blue Frog.
> http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D
>



-- 
-----
Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D

**Comment by interfaith** [comment]
yes avoiding minimongo IO did the trick ! no waiting now even for 300k data
update !

On Wed, Apr 20, 2016 at 9:34 AM, Mark Spowage <spowage@gmail.com> wrote:

> bjoindata.com seems to be ok with a window of 100 rows and page buttons
> for fine tuning.
> we'll go with this.
>
> the trick to avoid delay is to grab an array to avoid minimongo I/O
>
> trial and error rules.
>
> On Tue, Apr 19, 2016 at 11:23 AM, Mark Spowage <spowage@gmail.com> wrote:
>
>> The client side subscribe takes time to get "ready" a few seconds for
>> just 100 rows !
>> Should all client side records be erased before the window is moved ?
>>
>> On Tue, Apr 19, 2016 at 9:13 AM, Mark Spowage <spowage@gmail.com> wrote:
>>
>>> so far so good, see bjoindata.com login bjoindemo pwd bjoindemo
>>>
>>> run the select all query.
>>>
>>> for some reason it takes a second or 2 to render when the window is more
>>> than 400 rows.
>>>
>>> after the publish is done and the subscription is ready
>>>
>>> there is a way to know when the table is fully rendered ? using template
>>> rendered ?
>>>
>>> anyway we'll stay with reactive-table as it allows multi users.
>>>
>>> i should push an 'example' to github for others trying to do table
>>> displays.
>>>
>>>
>>> On Mon, Apr 18, 2016 at 6:17 PM, Amy Slagle <notifications@github.com>
>>> wrote:
>>>
>>>> Glad you got it to work! If you manage the pagination and filtering
>>>> yourself, you don't need ReactiveTable.publish and you can display whatever
>>>> data you want.
>>>>
>>>> —
>>>> You are receiving this because you modified the open/close state.
>>>> Reply to this email directly or view it on GitHub
>>>> <https://github.com/aslagle/reactive-table/issues/380#issuecomment-211669008>
>>>>
>>>
>>>
>>>
>>> --
>>> -----
>>> Fight back spam! Download the Blue Frog.
>>> http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D
>>>
>>
>>
>>
>> --
>> -----
>> Fight back spam! Download the Blue Frog.
>> http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D
>>
>
>
>
> --
> -----
> Fight back spam! Download the Blue Frog.
> http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D
>



-- 
-----
Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D

**Comment by interfaith** [comment]
Demo ready :)

bjoindata.com:3000
login demo/florida
dial 1 99
dial 2 99
select the target
you may need to click on add target then main menu to get the dials to show
some js trick is needed to keep it on the page

the tables are changing in real time and the 6 table join is updated in
real time
or created in real time
no other db engine can do this that we know of

the reactivejoin size changes each sec but the meteor update is about @ 5
sec
so i was pulling the change down if need be.

cheers !

On Tue, Apr 19, 2016 at 9:13 AM, Mark Spowage <spowage@gmail.com> wrote:

> so far so good, see bjoindata.com login bjoindemo pwd bjoindemo
>
> run the select all query.
>
> for some reason it takes a second or 2 to render when the window is more
> than 400 rows.
>
> after the publish is done and the subscription is ready
>
> there is a way to know when the table is fully rendered ? using template
> rendered ?
>
> anyway we'll stay with reactive-table as it allows multi users.
>
> i should push an 'example' to github for others trying to do table
> displays.
>
>
> On Mon, Apr 18, 2016 at 6:17 PM, Amy Slagle <notifications@github.com>
> wrote:
>
>> Glad you got it to work! If you manage the pagination and filtering
>> yourself, you don't need ReactiveTable.publish and you can display whatever
>> data you want.
>>
>> —
>> You are receiving this because you modified the open/close state.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/aslagle/reactive-table/issues/380#issuecomment-211669008>
>>
>
>
>
> --
> -----
> Fight back spam! Download the Blue Frog.
> http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D
>



-- 
-----
Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D

**Comment by interfaith** [comment]
oops
you must clik on the rowId TO INVERT the time order (rowId is just a
convenience column)
so YOUR table is the big win here
making it possible to view the VIRTUAL

On Fri, Jul 8, 2016 at 11:44 AM, Mark Spowage <spowage@gmail.com> wrote:

> Demo ready :)
>
> bjoindata.com:3000
> login demo/florida
> dial 1 99
> dial 2 99
> select the target
> you may need to click on add target then main menu to get the dials to show
> some js trick is needed to keep it on the page
>
> the tables are changing in real time and the 6 table join is updated in
> real time
> or created in real time
> no other db engine can do this that we know of
>
> the reactivejoin size changes each sec but the meteor update is about @ 5
> sec
> so i was pulling the change down if need be.
>
> cheers !
>
> On Tue, Apr 19, 2016 at 9:13 AM, Mark Spowage <spowage@gmail.com> wrote:
>
>> so far so good, see bjoindata.com login bjoindemo pwd bjoindemo
>>
>> run the select all query.
>>
>> for some reason it takes a second or 2 to render when the window is more
>> than 400 rows.
>>
>> after the publish is done and the subscription is ready
>>
>> there is a way to know when the table is fully rendered ? using template
>> rendered ?
>>
>> anyway we'll stay with reactive-table as it allows multi users.
>>
>> i should push an 'example' to github for others trying to do table
>> displays.
>>
>>
>> On Mon, Apr 18, 2016 at 6:17 PM, Amy Slagle <notifications@github.com>
>> wrote:
>>
>>> Glad you got it to work! If you manage the pagination and filtering
>>> yourself, you don't need ReactiveTable.publish and you can display whatever
>>> data you want.
>>>
>>> —
>>> You are receiving this because you modified the open/close state.
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/aslagle/reactive-table/issues/380#issuecomment-211669008>
>>>
>>
>>
>>
>> --
>> -----
>> Fight back spam! Download the Blue Frog.
>> http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D
>>
>
>
>
> --
> -----
> Fight back spam! Download the Blue Frog.
> http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D
>



-- 
-----
Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D

**Comment by interfaith** [comment]
for some reason.. meteor does not refresh after a while
so i use a timer to grab the window @3 sec :(

sure seems like a meteor issue
it reactively updates for a while and then 'sleeps'

On Tue, Apr 19, 2016 at 9:13 AM, Mark Spowage <spowage@gmail.com> wrote:

> so far so good, see bjoindata.com login bjoindemo pwd bjoindemo
>
> run the select all query.
>
> for some reason it takes a second or 2 to render when the window is more
> than 400 rows.
>
> after the publish is done and the subscription is ready
>
> there is a way to know when the table is fully rendered ? using template
> rendered ?
>
> anyway we'll stay with reactive-table as it allows multi users.
>
> i should push an 'example' to github for others trying to do table
> displays.
>
>
> On Mon, Apr 18, 2016 at 6:17 PM, Amy Slagle <notifications@github.com>
> wrote:
>
>> Glad you got it to work! If you manage the pagination and filtering
>> yourself, you don't need ReactiveTable.publish and you can display whatever
>> data you want.
>>
>> —
>> You are receiving this because you modified the open/close state.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/aslagle/reactive-table/issues/380#issuecomment-211669008>
>>
>
>
>
> --
> -----
> Fight back spam! Download the Blue Frog.
> http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D
>



-- 
-----
Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D

**Comment by interfaith** [comment]
how can one window into a large table of 100 million for example to see
just 1k ?
create a proxy collection and overwrite the entire proxy each time the
window is  moved ?
meteor really has no way to do it.. as meteor attempts to replicate the
entire collection.

On Tue, Apr 19, 2016 at 9:13 AM, Mark Spowage <spowage@gmail.com> wrote:

> so far so good, see bjoindata.com login bjoindemo pwd bjoindemo
>
> run the select all query.
>
> for some reason it takes a second or 2 to render when the window is more
> than 400 rows.
>
> after the publish is done and the subscription is ready
>
> there is a way to know when the table is fully rendered ? using template
> rendered ?
>
> anyway we'll stay with reactive-table as it allows multi users.
>
> i should push an 'example' to github for others trying to do table
> displays.
>
>
> On Mon, Apr 18, 2016 at 6:17 PM, Amy Slagle <notifications@github.com>
> wrote:
>
>> Glad you got it to work! If you manage the pagination and filtering
>> yourself, you don't need ReactiveTable.publish and you can display whatever
>> data you want.
>>
>> —
>> You are receiving this because you modified the open/close state.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/aslagle/reactive-table/issues/380#issuecomment-211669008>
>>
>
>
>
> --
> -----
> Fight back spam! Download the Blue Frog.
> http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D
>



-- 
-----
Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D

**Comment by aslagle** [comment]
You're right, it's not easy to do with Meteor. For ReactiveTable.publish I created a sort of proxy collection with a publication id added to each row, and changed the publication id every time I changed the subscription, so I could query it on the client before the old rows were removed. I don't think it's a very good solution though.
