### ISSUE TITLE
How to get the value of "getPageCount"?

### ISSUE THREAD

**Issue by aejaemiranda** [aslagle/reactive-table#381]
Im trying to display "Search result not found. " when the getPageCount = 0? is this possible? can you please give me a hint or sample? Thanks!

**Comment by aslagle** [comment]
That might be an option worth adding to the package, but it doesn't have anything like that now, sorry. If you're not using ReactiveTable.publish on the server, you can check the size of the collection to decide whether to display the table, but it wouldn't work with filtering.
