### ISSUE TITLE
Can't get current doc when use event handler ("template-controller").

### ISSUE THREAD

**Issue by thearabbit** [aslagle/reactive-table#388]
I use this with `template-controller` package.
It can't get current doc in table row when click event handler.
```js
// Don't work
TemplateController('Core_branch', {
    events:{
        'click .js-update' (event, instance) {
            console.log(this);// can not get current doc
        },
   }
});
```
And then I tried
```js
// Word fine
......
events: {
  'click .js-remove'(event, instance) {
     const doc = Blaze.getView(event.target).templateInstance();
     console.log(doc.data); // get {_id:..., name: ......}
  },
}
```
Why please help me.

**Comment by aslagle** [comment]
For this to refer to the current doc, the event target has to be the tr element, it can't be another element inside the row.

Take a look at the second example here, I think it's similar to what you're trying to do: https://github.com/aslagle/reactive-table#using-events

**Comment by thearabbit** [comment]
Thanks for your reply.
Now I tried `Blaze.getData(event.target)`, It work fine.
