### ISSUE TITLE
Filter gets cleared on collection update.

### ISSUE THREAD

**Issue by keyscores** [aslagle/reactive-table#392]
When an underlying collection is changed, the table seems to lose its filter. 

If I change the data with a form on the same page, I expect for the filter to stay there. Is there something  I'm overlooking in the docs?

I'm using the standard reactive table filter (not a custom). And I'm at the latest version ,  0.8.31.

**Comment by aslagle** [comment]
The only thing I can think of that would cause that is if the reactive table template is removed and rendered again. That would generate a new id which creates a new filter as well. If that's the problem, explicitly setting an id in the table arguments should make it use the same filter.

**Comment by keyscores** [comment]
Thanks @aslagle  that seems to have done the trick! Adding the ID made the behavior go away. Now I'm not sure why the table is re-rendering. We can close this, but I'll investigate further.
