### ISSUE TITLE
How to use "selector" from client?

### ISSUE THREAD

**Issue by thearabbit** [aslagle/reactive-table#393]
I have like this
```js
// Client
let setting = {
    collection: Post,
    selector: function(){
       return {createdDate: {..........}};
    }
............

// Both
Post = new Mongo.Collection('post');

// Server
ReactiveTable.publish("pubPost", Post);
```
But don't work, please help me.

**Comment by aslagle** [comment]
You can't pass in a selector from the client, but you can create a filter and put it in the table settings: https://github.com/aslagle/reactive-table#creating-your-own-filter

**Comment by thearabbit** [comment]
Thank, I don't​ want to create a filter form.
My project have multi branch such as: '001', '002'.....
When I login system with '001' branch, so my reactive table get the data with `branchId = 001`.

**Comment by aslagle** [comment]
You don't need to create a form to use a filter. You can create the filter and set it in your code - call `filter = new ReactiveTable.Filter("yourFilterId", ["branchId"])`, then `filter.set("001")` and pass the filter into the table settings: `filters: ["yourFilterId"]`. This is the only way to pass selectors from the client to the server.

**Comment by thearabbit** [comment]
Thanks again, I will try this.

**Comment by thearabbit** [comment]
Thanks, I tried it work fine.
But now I would like to filter with multiple fields, and have own conditions:
```js
filter = new ReactiveTable.Filter("yourFilterId", ["branchId",     "createdBy"])
filter.set("001") // branchId field
filter.set("Theara") // createdBy field
```

**Comment by aslagle** [comment]
You can add `showFilter: true` to your table settings and it will also display the normal filter box.

**Comment by thearabbit** [comment]
Thanks again, It work fine.
