### ISSUE TITLE
Could I use "TAPi18n" instead of "anti:i18n"?

### ISSUE THREAD

**Issue by thearabbit** [aslagle/reactive-table#398]
I use `Tapi18n`, so I would like to translate to `km`
```js
// reactive-table.km.i18n.json
{
  "reactiveTable": {
    "filter": "ស្វែងរក",
    "columns": "ជួរឈរ",
    "show": "បង្ហាញ",
    "rowsPerPage": "ជួរដេកក្នុងមួយទំព័រ",
    "page": "ទំព័រ",
    "of": "នៃ"
  }
}
```
But don't work, please help me.

**Comment by aslagle** [comment]
Sorry, anti:i18n is still the only option. See https://github.com/aslagle/reactive-table/issues/181. You can use tap:i18n for the rest of your app but add the anti:i18n package and set the language for reactive-table.

**Comment by thearabbit** [comment]
Now I install `anti:i18n`, it work fine.
Thanks
