### ISSUE TITLE
currentPage

### ISSUE THREAD

**Issue by amou1012** [aslagle/reactive-table#408]
I want to go back to the first page when I switch the data and I set currentPage in my tableSettings : 

 tableSettings(){
        return {
            showNavigation: 'auto',
            showRowCount: 'true',
            rowsPerPage: 10,
            currentPage: 0,
             fields: [.........]
       }
}

But I always stay at the page where I stayed at last time. Can anyone help me ? Thanks!!!!
![notification6](https://cloud.githubusercontent.com/assets/16955755/16721745/352ffebc-4774-11e6-84ff-4f8a00c913de.png)

**Comment by aslagle** [comment]
Make currentPage a ReactiveVar and then set it to 0 whenever you want to go to the first page.

```
// Put the variable somewhere accessible to table settings and the code you want to change it from.
var currentPage = new ReactiveVar();

...

tableSettings(){
return {
...
currentPage: currentPage,
...
}
}

...

// To go to the first page:
currentPage.set(0);
```

**Comment by amou1012** [comment]
It works !! Thanks a lot !!!!
