### ISSUE TITLE
Reset Table and showFilter after a click event

### ISSUE THREAD

**Issue by ndunhourowens** [aslagle/reactive-table#421]
Is there a way to reset the table back to the original state using a click event?

is the original state on rendered
<img width="378" alt="screen shot 2016-08-23 at 2 58 41 pm" src="https://cloud.githubusercontent.com/assets/12314014/17915002/792549ac-6942-11e6-8eb7-a65da8eb99dc.png">

user typing in filter
<img width="383" alt="screen shot 2016-08-23 at 2 58 54 pm" src="https://cloud.githubusercontent.com/assets/12314014/17915015/8fcbe68e-6942-11e6-9829-c5fbfb8ede01.png">

the click event is selecting the row.

after the click event i would like it to return back to the original state.  clearing the input box does not reset the table.  so far the only way to get back to the original state is to backspace what is typed in the input.

you're help is greatly appreciated.  thank you

**Comment by aslagle** [comment]
The keyup event is what actually updates the filter so you can trigger one on the input box after you clear it, like `$('.reactive-table-input').trigger('keyup')`.

**Comment by ndunhourowens** [comment]
This is what I have and it works for desktop.  How would this work for a mobile device when there is no way to create the "keyup" trigger?
$('.reactive-table-input').val("");
$('.reactive-table-input').trigger('keyup');

**Comment by aslagle** [comment]
I didn't know 'keyup' doesn't work on mobile. The filter also listens for the 'input' event, if that works. If not, does the filter box work at all on mobile?

**Comment by ndunhourowens** [comment]
I'm not sure, I just started building the app with the final product being able to use on mobile devices.  I haven't gotten that far to test it on a dev site, i just thinking ahead.
