### ISSUE TITLE
focus on $('.reactive-table-input')

### ISSUE THREAD

**Issue by ndunhourowens** [aslagle/reactive-table#423]
I've tried several different codes to have the cursor start in $('.reactive-table-input').  I'm using Meteor

1.  tried it on Render and create $('.reactive-table-input').focus();
2.  tried it in css .reactive-table-input:focus{background-color: yellow;}
3.  even in the html {{> reactiveTable settings=settings autofocus}}

#1 and #3 didn't do anything.  #2 did turn yellow when I clicked in the input box.

Any other suggestions?

Thank you

**Comment by aslagle** [comment]
Your first option should work, is this what you tried:
```
Template.myTemplate.onRendered(function() {
  $('.reactive-table-input').focus();
});
```

**Comment by ndunhourowens** [comment]
I tried that code, the cursor doesn't display in the input box.

**Comment by aslagle** [comment]
It works for me, so I don't know what could be wrong. Maybe there's something else in your app that's getting focus after the code runs?

**Comment by ndunhourowens** [comment]
This is the only item that I need the cursor to focus on.  The whole app is built around that particular input box and the results that is populated as user type.  I'm not sure either.  No worries.
