### ISSUE TITLE
Caption to Table

### ISSUE THREAD

**Issue by monasha-s** [aslagle/reactive-table#430]
How to provide caption to the Reactive Table? I need the caption as when exporting the table using caption I can rename the file. Is there a way to add it?

**Comment by aslagle** [comment]
Interesting, I hadn't heard of that tag before. The easiest thing would be to insert it with jquery after the template is rendered, like `$('.reactive-table thead').before('<caption>My Caption</caption>')`. That way there's no need to change the package.

**Comment by monasha-s** [comment]
Thank u, that worked
