### ISSUE TITLE
How to handle click event on an item inside tr

### ISSUE THREAD

**Issue by brascene** [aslagle/reactive-table#439]
I'm trying to achieve an event handling on span item inside a "tr - td" (edit icon), which will take me on another page for edit form. For now, I am able to achieve this successfully while clicking on "td" element  where my span icon is placed, but if I click on the icon itself, nothing happens. Can you help me with this, is it possible to catch this event and still be able to catch the row object?
Thanks!

**Comment by aslagle** [comment]
Take a look at the second example here: https://github.com/aslagle/reactive-table#using-events. You can add event handling to the tr element, but check the actual element that was clicked inside the event handler.

**Comment by brascene** [comment]
That example solved my issue, thanks! I made a mistake by checking event target class name as class name of field cell class :)
Thanks!
