### ISSUE TITLE
Rendering from JSON, escaping HTML tags.

### ISSUE THREAD

**Issue by emmanualojam** [aslagle/reactive-table#441]
Pls how do I render content from JSON that contains HTML tags as HTML, pls permit my ignorance am new to meteor and I have been search this questions for days without an answer. 

for example I want to display this as html not text in the table 

> &lt;p&gt;&lt;a href="https://jobs.lever.co/canva/3f8de580-e99b-4cb2-8d31-8f49d37d11d8/apply?lever-source=GithubJobs"&gt;https://jobs.lever.co/canva/3f8de580-e99b-4cb2-8d31-8f49d37d11d8/apply?lever-source=GithubJobs&lt;/a&gt;&lt;/p&gt;

as this

<p><a href="https://jobs.lever.co/canva/3f8de580-e99b-4cb2-8d31-8f49d37d11d8/apply?lever-source=GithubJobs">https://jobs.lever.co/canva/3f8de580-e99b-4cb2-8d31-8f49d37d11d8/apply?lever-source=GithubJobs</a></p>

**Comment by aslagle** [comment]
You have to use Spacebars.SafeString for Blaze to render the html:

```
new Spacebars.SafeString("<p><a href="https://jobs.lever.co/canva/3f8de580-e99b-4cb2-8d31-8f49d37d11d8/apply?lever-source=GithubJobs"&gt;https://jobs.lever.co/canva/3f8de580-e99b-4cb2-8d31-8f49d37d11d8/apply?lever-source=GithubJobs&lt;/a&gt;&lt;/p>");
```

**Comment by emmanualojam** [comment]
Ok but the content are from an api so can Ido this 
   const show = new Spacebars.SafeString(JSON.parse(result.content));

**Comment by aslagle** [comment]
You would need to change the fields in your settings so that any of the fields that contain HTML call Spacebars.SafeString.

Something like:
```
fields: [
  'created_at',
  'company',
  { key: 'title', label: 'title', fn: function (value) { return new Spacebars.SafeString(value) }; },
  'type',
   { key: 'how_to_apply', label: 'how to apply', fn: function (value) { return new Spacebars.SafeString(value) }; },
]
```

**Comment by emmanualojam** [comment]
Problem solved thanks a lot really appreciate your time.
