### ISSUE TITLE
Chrome button click in table cell un-responsive

### ISSUE THREAD

**Issue by bryantbiggs** [aslagle/reactive-table#452]
When using Chrome, the buttons inside my table are un-responsive and usually takes multiple clicks before the event is fired. In Firefox and Safari there are no issues. 

`{
label: 'Contact',
fn: function(value, object) { const btn = '<button name="btn_contact" class="primary basic ui icon button"> <i class="mail outline icon"></i> </button>';
return new Spacebars.SafeString(btn);
}`

**Comment by aslagle** [comment]
I don't know what would cause that. There aren't any click event handlers on the table rows that would interfere with it.

**Comment by bryantbiggs** [comment]
This was an error on my end. Changing the html from "name" to "id" allowed the button clicks to be picked up and fire.
