### ISSUE TITLE
Get access to row object in template function

### ISSUE THREAD

**Issue by spiotr12** [aslagle/reactive-table#453]
This might be more as dev request:

It would be great to pass current collection object to the tmpl function for fields

Reason: use different templates depend on value. Is this would be possible.

`this` does not access the collection object

E.g.:
```
tmpl: function (value, object, key) {
	if (value = 'foo') {
		return Template.details_field;
	}
}
```

**Comment by aslagle** [comment]
It is possible to write a template that checks the value and renders different templates, but I guess it's not as convenient as it could be.

**Comment by spiotr12** [comment]
The way I finally solve it was to create a template helper which was rendering different text <- so similarly to way you suggest
