### ISSUE TITLE
`click .reactive-table` event on cell : ok except on cell content

### ISSUE THREAD

**Issue by Ontokrat** [aslagle/reactive-table#456]
Hi,
I have, on a click on a cell in each line (column with a `cellClass`), an event.
In this cell, there is some html (icon), called by `Spacebars.SafeString`

Everything works very fine if I click on the cell but not on the content injected in it (icon).
If I inject in the cell just simple text with no html, everything works fine (click on content as everywhere else in the cell).

Below my code: the event is managed just as written in the [docs](https://github.com/aslagle/reactive-table#using-events) (second code example for managing `className`).

How can I fix that ? Thanks.

**Try #1 (use of `Spacebars.SafeString` in a function)**
```
{ key: 'delete',
    cellClass: 'delete-message',
    label: 'Delete',
    fn: function (value) { 
    return new Spacebars.SafeString(`<a class="makepdf"><i class="fa fa-trash-o" aria-hidden="true"></i></a>`);
    }
}
```

**Try #2 (use of external template to insert html)**
```
  { key: 'Answer',
    cellClass: 'reply-message',
    tmpl: Template.replybutton,
    label: 'Answer'
  }
```

**Comment by aslagle** [comment]
I think the problem is that when you click on the icon, event.target will be the i element or the a element, rather than the cell. So in addition to checking event.target.className in the event handler you'll need to check event.target.parentElement.className or event.target.parentElement.parentElement.className.

**Comment by Ontokrat** [comment]
@aslagle Thanks for the answer. Could you be a little bit more specific?
I understand the idea of your answer, but don't know how to implement it.
Below my code (linked to my `Try #1` code in my question) : 

```
Template.UserProfileEdit.events({
  'click .reactive-table tbody tr': function (event) {
    // Delete message
    if (event.target.className == "delete-message") {
```

**Comment by aslagle** [comment]
something like `if (event.target.className == "delete-message" || event.target.parentElement.className == "delete-message" || event.target.parentElement.parentElement.className == "delete-message") {`

**Comment by Ontokrat** [comment]
Of course, I was wondering 'how can I catch the `parentElement` name?' Problem with working way too late..
Thanks again, everything's fine. Maybe you should add this precision in your `readme` : using icons to represent `edit` or `delete` functions are pretty basic usage. Have a nice day.
