### ISSUE TITLE
Related Custom Filter

### ISSUE THREAD

**Issue by peeyushjss** [aslagle/reactive-table#458]
Hello @aslagle 

I wanna ask something about custom filter. I made a new custom filter with the given code - 

Template.filter = new ReactiveTable.Filter('city', ["city"]);
ReactiveTable.Filter('city').set('Noida');

Can we set value in the array format in place of String? I mean to say If we want data show who's city is Noida and some else also. So How can I set it?
eg: 

Template.filter = new ReactiveTable.Filter('city', ["city"]);
ReactiveTable.Filter('city').set(['Noida', 'Delhi']);

It's not working. 

One more issue can we set more than one key, when show data in reactive table. eg-

 {
        key: 'barcodeScanner.connected', // barcodeScanner.connected && barcodeScanner.status
        label: 'Barcode Scanner',
        fn: function(value, object) {
          if (value)
            return new Spacebars.SafeString('<div class="glance-device-status terminal-device-status" style="margin: 6px 0px;"><span class="status-ok"></span></div>');
          else {
            return new Spacebars.SafeString('<div class="glance-device-status terminal-device-status" style="margin: 6px 0px;"><span class="status-error"></span></div>');
          }
        }
      }

Please provide me solution as soon as fast. Thanks in advance.

**Comment by peeyushjss** [comment]
@is-undefined I tried several things and also read documentation then asked question.

If you have any solution please provide me.

**Comment by aslagle** [comment]
For the first question, the custom filter won't work with anything except a string or a simple mongo selector like `$gt`, but you might be able to set the `filterOperator` in the overall table settings to `"$or"` and then use the string `"Noida Delhi"` to find rows that match either word.

For the second question, there can only be one key but you can access the value for any other key using the `object` argument - it contains all keys for that row.

**Comment by peeyushjss** [comment]
For the second question, there can only be one key but you can access the value for any other key using the object argument - it contains all keys for that row.
 I understand it but I have another point. concentrate on given line

key: 'barcodeScanner.connected', // barcodeScanner.connected && barcodeScanner.status

can we use as key : 'barcodeScanner.connected && barcodeScanner.status'

or 
can we use as key : 'barcodeScanner.connected || barcodeScanner.status'.

I tried object but custom filter works on the key.

**Comment by peeyushjss** [comment]
Thanks for reply @aslagle I have one more question related to custom filter.

If we don't have particular key in collection. filter not working. Can you have any solution for this.

**Comment by aslagle** [comment]
No, you can't use more than one thing in the key. You'll have to pick one of them, and use `object` to get the other one inside your `fn`.

**Comment by peeyushjss** [comment]
Thanks for confirming me.
