### ISSUE TITLE
Row numbering Excel-style

### ISSUE THREAD

**Issue by naho2081** [aslagle/reactive-table#474]
Is it possible to add numbers to the table rows like this?
1.
2.
3...

Actually it is number of the row in the reactiveTable.
If I move to Page 2 (assuming I have 50 rows per page) numbers should continue like this
51.
52.
53..

**Comment by naho2081** [comment]
Solved this using CSS.
It doesn't take into account pagination but at least rows have numbers.

```
table
  counter-reset rowNumber
  tbody
    tr
      counter-increment rowNumber
      td
        &:first-child
          &::before
            content counter(rowNumber)
            min-width 1em
            margin-right 1em
```

**Comment by aslagle** [comment]
I'm glad you figured something out. I don't think there's a better way to do this unless you store numbers with your data.
