### ISSUE TITLE
Client-side change page number through custom button

### ISSUE THREAD

**Issue by maltahs** [aslagle/reactive-table#477]
Hi,

First of all, this is a great library! 

I've been trying to create customised client-side buttons to allow for navigation through the pages, but have no idea how to make it work. Is there a specific method I can add to my client-side event listener that can change the page?

I looked at the existing element for "next page", [class="next-page fa fa-caret-right"]  but couldn't find the relevant click event to trigger page change. Would be grateful if someone can assist.

Thanks.

**Comment by aslagle** [comment]
Hi, I think the best way to do this would be to use a ReactiveVar for the current page like in [this example](https://github.com/aslagle/reactive-table/blob/master/examples/saved-state/leaderboard.js). The example uses the ReactiveVar to save the current page to the session, but you can also set the ReactiveVar from your event listener to change the page the table is showing.

**Comment by maltahs** [comment]
Thanks you for the response! I shall give it a try this week.

**Comment by maltahs** [comment]
Your suggestion worked like a charm. 

I used the ReactiveVar, which then I incremented / decremented via the respective custom button event handlers.

Thank you for pointing me to the right direction.
